AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kansousen

Globals:
  Function:
    Timeout: 5

Parameters:
  Stage:
    Type: String
    Default: prod
  ApiDomainName:
    Type: String
  SiteDomainName:
    Type: String
  AuthDomainName:
    Type: String
  Certificate:
    Type: String
  CognitoCertificate:
    Type: String

Resources:
  KansousenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: kifuId
          AttributeType: S
        - AttributeName: var
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdTs
          AttributeType: N
        - AttributeName: startTs
          AttributeType: N
        - AttributeName: sfen
          AttributeType: S
        - AttributeName: pos
          AttributeType: S
      KeySchema:
        - AttributeName: kifuId
          KeyType: HASH
        - AttributeName: var
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: Created
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdTs
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - kifu
              - version
        - IndexName: Start
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: startTs
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - kifu
              - version
        - IndexName: Sfen
          KeySchema:
            - AttributeName: sfen
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: Position
          KeySchema:
            - AttributeName: pos
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - userId
              - seq

  KansousenTablePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
              - dynamodb:DescribeTable
              - dynamodb:PutItem
              - dynamodb:BatchWriteItem
              - dynamodb:DeleteItem
            Resource:
              - !GetAtt KansousenTable.Arn
              - !Sub
                - "${TableARN}/index/*"
                - { TableARN: !GetAtt KansousenTable.Arn }

  KifuFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/kifu
      Handler: kifu
      Runtime: go1.x
      Policies: !Ref KansousenTablePolicy
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          TABLE_NAME: !Ref KansousenTable

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: False
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: False
          RequireNumbers: False
          RequireSymbols: False
          RequireUppercase: False
          TemporaryPasswordValidityDays: 7
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Priority: 1
            Name: verified_email
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      SupportedIdentityProviders:
        - COGNITO
      GenerateSecret: false
      CallbackURLs:
        - !Sub "https://${SiteDomainName}/callback"
        - http://localhost:8080/callback
      LogoutURLs:
        - !Sub "https://${SiteDomainName}/"
        - http://localhost:8080/
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      TokenValidityUnits:
        IdToken: "hours"
        AccessToken: "hours"
        RefreshToken: "days"
      IdTokenValidity: 1
      AccessTokenValidity: 1
      RefreshTokenValidity: 30

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Domain: !Ref AuthDomainName
      CustomDomainConfig:
        CertificateArn: !Ref CognitoCertificate

  KifuApiV2:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      CorsConfiguration:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'POST'"
        AllowOrigins: "'*'"
      Domain:
        DomainName: !Ref ApiDomainName
        CertificateArn: !Ref Certificate
        SecurityPolicy: TLS_1_2
        EndpointConfiguration: REGIONAL
      Auth:
        Authorizers:
          OAuth2Authorizer:
            IdentitySource: '$request.header.Authorization'
            JwtConfiguration:
              audience: !Ref CognitoUserPoolClient
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}"
        DefaultAuthorizer: OAuth2Authorizer

  KifuApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/kifu
      Handler: kifu
      Runtime: go1.x
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt KifuFunction.Arn
      Environment:
        Variables:
          CONFIG_URL: !Sub "https://${SiteDomainName}/config.json"
      Events:
        KifuApiEvent:
          Type: HttpApi
          Properties:
            Path: /v1/{proxy+}
            Method: POST
            ApiId: !Ref KifuApiV2

  HealthApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/ok
      Handler: ok
      Runtime: go1.x
      Policies: !Ref KansousenTablePolicy
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          TABLE_NAME: !Ref KansousenTable
      Events:
        HealthApiEvent:
          Type: HttpApi
          Properties:
            Path: /v1/ok
            Method: GET
            ApiId: !Ref KifuApiV2
            Auth:
              Authorizer: NONE

  UIBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  UIApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${AWS::StackName}-UI"
      EndpointConfiguration:
        Types:
          - REGIONAL

  UIApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service: apigateway.amazonaws.com
      Policies:
        - PolicyName: GetObject
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "${UIBucket.Arn}/*"

  UIMethodRootGET:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref UIApi
      ResourceId: !GetAtt UIApi.RootResourceId
      AuthorizationType: NONE
      HttpMethod: GET
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Content-Type: true
          ResponseModels:
            text/html: Empty
      Integration:
        Type: AWS
        IntegrationHttpMethod: GET
        Uri: !Join
          - ":"
          - - arn
            - !Ref AWS::Partition
            - apigateway
            - !Ref AWS::Region
            - s3
            - !Join
              - "/"
              - - path
                - !Ref UIBucket
                - index.html
        Credentials: !GetAtt UIApiRole.Arn
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Content-Type: integration.response.header.Content-Type

  UIResourceItem:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref UIApi
      ParentId: !GetAtt UIApi.RootResourceId
      PathPart: "{item+}"

  UIMethodItemGET:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref UIApi
      ResourceId: !Ref UIResourceItem
      AuthorizationType: NONE
      HttpMethod: GET
      RequestParameters:
        method.request.path.item: true
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Content-Type: true
          ResponseModels:
            application/octet-stream: Empty
            application/json: Empty
            text/plain: Empty
            text/html: Empty
            text/css: Empty
            text/javascript: Empty
            image/png: Empty
            image/jpeg: Empty
            image/svg+xml: Empty
            image/vnd.microsoft.icon: Empty
      Integration:
        Type: AWS
        IntegrationHttpMethod: GET
        Uri: !Join
          - ":"
          - - arn
            - !Ref AWS::Partition
            - apigateway
            - !Ref AWS::Region
            - s3
            - !Join
              - "/"
              - - path
                - !Ref UIBucket
                - "{item}"
        Credentials: !GetAtt UIApiRole.Arn
        RequestParameters:
          integration.request.path.item: method.request.path.item
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Content-Type: integration.response.header.Content-Type

  UIDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref SiteDomainName
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref Certificate
      SecurityPolicy: TLS_1_2

  UIDeployment2021100401:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - UIMethodRootGET
      - UIResourceItem
      - UIMethodItemGET
    Properties:
      RestApiId: !Ref UIApi

  UIApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Ref Stage
      RestApiId: !Ref UIApi
      DeploymentId: !Ref UIDeployment2021100401

  UIDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn:
      - UIDomain
    Properties:
      RestApiId: !Ref UIApi
      DomainName: !Ref SiteDomainName
      Stage: !Ref UIApiStage

Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region
  StackName:
    Description: "StackName"
    Value: !Ref AWS::StackName
  KifuTable:
    Description: "Table name for Kifu"
    Value: !Ref KansousenTable
  KifuFunction:
    Description: "KifuFunction Arn"
    Value: !GetAtt KifuFunction.Arn
  UserPoolClientID:
    Description: "User Pool Client ID"
    Value: !Ref CognitoUserPoolClient
  ApiID:
    Description: "API ID"
    Value: !Ref KifuApiV2
  Host:
    Description: "Host URL"
    Value: !Sub "https://${SiteDomainName}/"
  IDP:
    Description: "IDP URL"
    Value: !Sub "https://${AuthDomainName}/"
  UIBucket:
    Description: "Bucket"
    Value: !Ref UIBucket
