// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: proto/document.proto

package document

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Player_Order int32

const (
	Player_BLACK Player_Order = 0
	Player_WHITE Player_Order = 1
)

// Enum value maps for Player_Order.
var (
	Player_Order_name = map[int32]string{
		0: "BLACK",
		1: "WHITE",
	}
	Player_Order_value = map[string]int32{
		"BLACK": 0,
		"WHITE": 1,
	}
)

func (x Player_Order) Enum() *Player_Order {
	p := new(Player_Order)
	*p = x
	return p
}

func (x Player_Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Player_Order) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_document_proto_enumTypes[0].Descriptor()
}

func (Player_Order) Type() protoreflect.EnumType {
	return &file_proto_document_proto_enumTypes[0]
}

func (x Player_Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Player_Order.Descriptor instead.
func (Player_Order) EnumDescriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{0, 0}
}

type FinishedStatus_Id int32

const (
	FinishedStatus_NOT_FINISHED    FinishedStatus_Id = 0
	FinishedStatus_SUSPEND         FinishedStatus_Id = 1
	FinishedStatus_SURRENDER       FinishedStatus_Id = 2
	FinishedStatus_DRAW            FinishedStatus_Id = 3
	FinishedStatus_REPETITION_DRAW FinishedStatus_Id = 4
	FinishedStatus_CHECKMATE       FinishedStatus_Id = 5
	FinishedStatus_OVER_TIME_LIMIT FinishedStatus_Id = 6
	FinishedStatus_FOUL_LOSS       FinishedStatus_Id = 7
	FinishedStatus_FOUL_WIN        FinishedStatus_Id = 8
	FinishedStatus_NYUGYOKU_WIN    FinishedStatus_Id = 9
)

// Enum value maps for FinishedStatus_Id.
var (
	FinishedStatus_Id_name = map[int32]string{
		0: "NOT_FINISHED",
		1: "SUSPEND",
		2: "SURRENDER",
		3: "DRAW",
		4: "REPETITION_DRAW",
		5: "CHECKMATE",
		6: "OVER_TIME_LIMIT",
		7: "FOUL_LOSS",
		8: "FOUL_WIN",
		9: "NYUGYOKU_WIN",
	}
	FinishedStatus_Id_value = map[string]int32{
		"NOT_FINISHED":    0,
		"SUSPEND":         1,
		"SURRENDER":       2,
		"DRAW":            3,
		"REPETITION_DRAW": 4,
		"CHECKMATE":       5,
		"OVER_TIME_LIMIT": 6,
		"FOUL_LOSS":       7,
		"FOUL_WIN":        8,
		"NYUGYOKU_WIN":    9,
	}
)

func (x FinishedStatus_Id) Enum() *FinishedStatus_Id {
	p := new(FinishedStatus_Id)
	*p = x
	return p
}

func (x FinishedStatus_Id) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinishedStatus_Id) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_document_proto_enumTypes[1].Descriptor()
}

func (FinishedStatus_Id) Type() protoreflect.EnumType {
	return &file_proto_document_proto_enumTypes[1]
}

func (x FinishedStatus_Id) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinishedStatus_Id.Descriptor instead.
func (FinishedStatus_Id) EnumDescriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{1, 0}
}

type Handicap_Id int32

const (
	Handicap_NONE        Handicap_Id = 0
	Handicap_DROP_L      Handicap_Id = 1
	Handicap_DROP_L_R    Handicap_Id = 2
	Handicap_DROP_B      Handicap_Id = 3
	Handicap_DROP_R      Handicap_Id = 4
	Handicap_DROP_RL     Handicap_Id = 5
	Handicap_DROP_TWO    Handicap_Id = 6
	Handicap_DROP_THREE  Handicap_Id = 7
	Handicap_DROP_FOUR   Handicap_Id = 8
	Handicap_DROP_FIVE   Handicap_Id = 9
	Handicap_DROP_FIVE_L Handicap_Id = 10
	Handicap_DROP_SIX    Handicap_Id = 11
	Handicap_DROP_EIGHT  Handicap_Id = 12
	Handicap_DROP_TEN    Handicap_Id = 13
	Handicap_OTHER       Handicap_Id = 14
)

// Enum value maps for Handicap_Id.
var (
	Handicap_Id_name = map[int32]string{
		0:  "NONE",
		1:  "DROP_L",
		2:  "DROP_L_R",
		3:  "DROP_B",
		4:  "DROP_R",
		5:  "DROP_RL",
		6:  "DROP_TWO",
		7:  "DROP_THREE",
		8:  "DROP_FOUR",
		9:  "DROP_FIVE",
		10: "DROP_FIVE_L",
		11: "DROP_SIX",
		12: "DROP_EIGHT",
		13: "DROP_TEN",
		14: "OTHER",
	}
	Handicap_Id_value = map[string]int32{
		"NONE":        0,
		"DROP_L":      1,
		"DROP_L_R":    2,
		"DROP_B":      3,
		"DROP_R":      4,
		"DROP_RL":     5,
		"DROP_TWO":    6,
		"DROP_THREE":  7,
		"DROP_FOUR":   8,
		"DROP_FIVE":   9,
		"DROP_FIVE_L": 10,
		"DROP_SIX":    11,
		"DROP_EIGHT":  12,
		"DROP_TEN":    13,
		"OTHER":       14,
	}
)

func (x Handicap_Id) Enum() *Handicap_Id {
	p := new(Handicap_Id)
	*p = x
	return p
}

func (x Handicap_Id) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Handicap_Id) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_document_proto_enumTypes[2].Descriptor()
}

func (Handicap_Id) Type() protoreflect.EnumType {
	return &file_proto_document_proto_enumTypes[2]
}

func (x Handicap_Id) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Handicap_Id.Descriptor instead.
func (Handicap_Id) EnumDescriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{2, 0}
}

type Piece_Id int32

const (
	Piece_NULL      Piece_Id = 0
	Piece_GYOKU     Piece_Id = 1
	Piece_HISHA     Piece_Id = 2
	Piece_RYU       Piece_Id = 3
	Piece_KAKU      Piece_Id = 4
	Piece_UMA       Piece_Id = 5
	Piece_KIN       Piece_Id = 6
	Piece_GIN       Piece_Id = 7
	Piece_NARI_GIN  Piece_Id = 8
	Piece_KEI       Piece_Id = 9
	Piece_NARI_KEI  Piece_Id = 10
	Piece_KYOU      Piece_Id = 11
	Piece_NARI_KYOU Piece_Id = 12
	Piece_FU        Piece_Id = 13
	Piece_TO        Piece_Id = 14
)

// Enum value maps for Piece_Id.
var (
	Piece_Id_name = map[int32]string{
		0:  "NULL",
		1:  "GYOKU",
		2:  "HISHA",
		3:  "RYU",
		4:  "KAKU",
		5:  "UMA",
		6:  "KIN",
		7:  "GIN",
		8:  "NARI_GIN",
		9:  "KEI",
		10: "NARI_KEI",
		11: "KYOU",
		12: "NARI_KYOU",
		13: "FU",
		14: "TO",
	}
	Piece_Id_value = map[string]int32{
		"NULL":      0,
		"GYOKU":     1,
		"HISHA":     2,
		"RYU":       3,
		"KAKU":      4,
		"UMA":       5,
		"KIN":       6,
		"GIN":       7,
		"NARI_GIN":  8,
		"KEI":       9,
		"NARI_KEI":  10,
		"KYOU":      11,
		"NARI_KYOU": 12,
		"FU":        13,
		"TO":        14,
	}
)

func (x Piece_Id) Enum() *Piece_Id {
	p := new(Piece_Id)
	*p = x
	return p
}

func (x Piece_Id) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Piece_Id) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_document_proto_enumTypes[3].Descriptor()
}

func (Piece_Id) Type() protoreflect.EnumType {
	return &file_proto_document_proto_enumTypes[3]
}

func (x Piece_Id) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Piece_Id.Descriptor instead.
func (Piece_Id) EnumDescriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{3, 0}
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order Player_Order `protobuf:"varint,1,opt,name=order,proto3,enum=document.Player_Order" json:"order,omitempty"`
	Name  string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Note  string       `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_document_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetOrder() Player_Order {
	if x != nil {
		return x.Order
	}
	return Player_BLACK
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type FinishedStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishedStatus) Reset() {
	*x = FinishedStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_document_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishedStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishedStatus) ProtoMessage() {}

func (x *FinishedStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishedStatus.ProtoReflect.Descriptor instead.
func (*FinishedStatus) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{1}
}

type Handicap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Handicap) Reset() {
	*x = Handicap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_document_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Handicap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handicap) ProtoMessage() {}

func (x *Handicap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handicap.ProtoReflect.Descriptor instead.
func (*Handicap) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{2}
}

type Piece struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Piece) Reset() {
	*x = Piece{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_document_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Piece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Piece) ProtoMessage() {}

func (x *Piece) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Piece.ProtoReflect.Descriptor instead.
func (*Piece) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{3}
}

type Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Pos) Reset() {
	*x = Pos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_document_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{4}
}

func (x *Pos) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pos) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Kifu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string            `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KifuId      string            `protobuf:"bytes,2,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	StartTs     int64             `protobuf:"varint,4,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	EndTs       int64             `protobuf:"varint,5,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	Handicap    Handicap_Id       `protobuf:"varint,6,opt,name=handicap,proto3,enum=document.Handicap_Id" json:"handicap,omitempty"`
	GameName    string            `protobuf:"bytes,7,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	Players     []*Player         `protobuf:"bytes,8,rep,name=players,proto3" json:"players,omitempty"`
	OtherFields map[string]string `protobuf:"bytes,9,rep,name=other_fields,json=otherFields,proto3" json:"other_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sfen        string            `protobuf:"bytes,10,opt,name=sfen,proto3" json:"sfen,omitempty"`
	Aliases     []string          `protobuf:"bytes,11,rep,name=aliases,proto3" json:"aliases,omitempty"`
	CreatedTs   int64             `protobuf:"varint,12,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	Note        string            `protobuf:"bytes,13,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *Kifu) Reset() {
	*x = Kifu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_document_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kifu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kifu) ProtoMessage() {}

func (x *Kifu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kifu.ProtoReflect.Descriptor instead.
func (*Kifu) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{5}
}

func (x *Kifu) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Kifu) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

func (x *Kifu) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *Kifu) GetEndTs() int64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *Kifu) GetHandicap() Handicap_Id {
	if x != nil {
		return x.Handicap
	}
	return Handicap_NONE
}

func (x *Kifu) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *Kifu) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Kifu) GetOtherFields() map[string]string {
	if x != nil {
		return x.OtherFields
	}
	return nil
}

func (x *Kifu) GetSfen() string {
	if x != nil {
		return x.Sfen
	}
	return ""
}

func (x *Kifu) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *Kifu) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *Kifu) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string            `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KifuId         string            `protobuf:"bytes,2,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	Seq            int32             `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Position       string            `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Src            *Pos              `protobuf:"bytes,6,opt,name=src,proto3" json:"src,omitempty"`
	Dst            *Pos              `protobuf:"bytes,7,opt,name=dst,proto3" json:"dst,omitempty"`
	Piece          Piece_Id          `protobuf:"varint,8,opt,name=piece,proto3,enum=document.Piece_Id" json:"piece,omitempty"`
	Promote        bool              `protobuf:"varint,9,opt,name=promote,proto3" json:"promote,omitempty"`
	Drop           bool              `protobuf:"varint,10,opt,name=drop,proto3" json:"drop,omitempty"`
	Captured       Piece_Id          `protobuf:"varint,11,opt,name=captured,proto3,enum=document.Piece_Id" json:"captured,omitempty"`
	FinishedStatus FinishedStatus_Id `protobuf:"varint,12,opt,name=finished_status,json=finishedStatus,proto3,enum=document.FinishedStatus_Id" json:"finished_status,omitempty"`
	Sfen           string            `protobuf:"bytes,13,opt,name=sfen,proto3" json:"sfen,omitempty"`
	TimestampSec   int32             `protobuf:"varint,14,opt,name=timestamp_sec,json=timestampSec,proto3" json:"timestamp_sec,omitempty"`
	ThinkingSec    int32             `protobuf:"varint,15,opt,name=thinking_sec,json=thinkingSec,proto3" json:"thinking_sec,omitempty"`
	Notes          []string          `protobuf:"bytes,16,rep,name=notes,proto3" json:"notes,omitempty"`
}

func (x *Step) Reset() {
	*x = Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_document_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{6}
}

func (x *Step) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Step) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

func (x *Step) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Step) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Step) GetSrc() *Pos {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *Step) GetDst() *Pos {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *Step) GetPiece() Piece_Id {
	if x != nil {
		return x.Piece
	}
	return Piece_NULL
}

func (x *Step) GetPromote() bool {
	if x != nil {
		return x.Promote
	}
	return false
}

func (x *Step) GetDrop() bool {
	if x != nil {
		return x.Drop
	}
	return false
}

func (x *Step) GetCaptured() Piece_Id {
	if x != nil {
		return x.Captured
	}
	return Piece_NULL
}

func (x *Step) GetFinishedStatus() FinishedStatus_Id {
	if x != nil {
		return x.FinishedStatus
	}
	return FinishedStatus_NOT_FINISHED
}

func (x *Step) GetSfen() string {
	if x != nil {
		return x.Sfen
	}
	return ""
}

func (x *Step) GetTimestampSec() int32 {
	if x != nil {
		return x.TimestampSec
	}
	return 0
}

func (x *Step) GetThinkingSec() int32 {
	if x != nil {
		return x.ThinkingSec
	}
	return 0
}

func (x *Step) GetNotes() []string {
	if x != nil {
		return x.Notes
	}
	return nil
}

var File_proto_document_proto protoreflect.FileDescriptor

var file_proto_document_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x22, 0x7d, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65,
	0x22, 0x1d, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x4c, 0x41,
	0x43, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x48, 0x49, 0x54, 0x45, 0x10, 0x01, 0x22,
	0xb7, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x54,
	0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x55, 0x53, 0x50, 0x45, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55, 0x52, 0x52,
	0x45, 0x4e, 0x44, 0x45, 0x52, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x52, 0x41, 0x57, 0x10,
	0x03, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x50, 0x45, 0x54, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x44, 0x52, 0x41, 0x57, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x4d,
	0x41, 0x54, 0x45, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x56, 0x45, 0x52, 0x5f, 0x54, 0x49,
	0x4d, 0x45, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x4f,
	0x55, 0x4c, 0x5f, 0x4c, 0x4f, 0x53, 0x53, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x4f, 0x55,
	0x4c, 0x5f, 0x57, 0x49, 0x4e, 0x10, 0x08, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x59, 0x55, 0x47, 0x59,
	0x4f, 0x4b, 0x55, 0x5f, 0x57, 0x49, 0x4e, 0x10, 0x09, 0x22, 0xde, 0x01, 0x0a, 0x08, 0x48, 0x61,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x70, 0x22, 0xd1, 0x01, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x08, 0x0a,
	0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x52, 0x4f, 0x50, 0x5f,
	0x4c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x4c, 0x5f, 0x52, 0x10,
	0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x42, 0x10, 0x03, 0x12, 0x0a, 0x0a,
	0x06, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x52, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x52, 0x4f,
	0x50, 0x5f, 0x52, 0x4c, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x54,
	0x57, 0x4f, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x54, 0x48, 0x52,
	0x45, 0x45, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x46, 0x4f, 0x55,
	0x52, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x46, 0x49, 0x56, 0x45,
	0x10, 0x09, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x46, 0x49, 0x56, 0x45, 0x5f,
	0x4c, 0x10, 0x0a, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x53, 0x49, 0x58, 0x10,
	0x0b, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x45, 0x49, 0x47, 0x48, 0x54, 0x10,
	0x0c, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x54, 0x45, 0x4e, 0x10, 0x0d, 0x12,
	0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x0e, 0x22, 0xaa, 0x01, 0x0a, 0x05, 0x50,
	0x69, 0x65, 0x63, 0x65, 0x22, 0xa0, 0x01, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x59, 0x4f, 0x4b, 0x55, 0x10, 0x01,
	0x12, 0x09, 0x0a, 0x05, 0x48, 0x49, 0x53, 0x48, 0x41, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x52,
	0x59, 0x55, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x41, 0x4b, 0x55, 0x10, 0x04, 0x12, 0x07,
	0x0a, 0x03, 0x55, 0x4d, 0x41, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x4b, 0x49, 0x4e, 0x10, 0x06,
	0x12, 0x07, 0x0a, 0x03, 0x47, 0x49, 0x4e, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x41, 0x52,
	0x49, 0x5f, 0x47, 0x49, 0x4e, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x4b, 0x45, 0x49, 0x10, 0x09,
	0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x41, 0x52, 0x49, 0x5f, 0x4b, 0x45, 0x49, 0x10, 0x0a, 0x12, 0x08,
	0x0a, 0x04, 0x4b, 0x59, 0x4f, 0x55, 0x10, 0x0b, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x41, 0x52, 0x49,
	0x5f, 0x4b, 0x59, 0x4f, 0x55, 0x10, 0x0c, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x55, 0x10, 0x0d, 0x12,
	0x06, 0x0a, 0x02, 0x54, 0x4f, 0x10, 0x0e, 0x22, 0x21, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0xcb, 0x03, 0x0a, 0x04, 0x4b,
	0x69, 0x66, 0x75, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b,
	0x69, 0x66, 0x75, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x73,
	0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x65, 0x6e, 0x64, 0x54, 0x73, 0x12, 0x31, 0x0a, 0x08, 0x68, 0x61, 0x6e, 0x64, 0x69,
	0x63, 0x61, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x70, 0x2e, 0x49, 0x64,
	0x52, 0x08, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67,
	0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x12, 0x42, 0x0a, 0x0c, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4b, 0x69, 0x66, 0x75, 0x2e, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x6f, 0x74, 0x68, 0x65,
	0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x66, 0x65, 0x6e, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x66, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c,
	0x69, 0x61, 0x73, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x74, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x1a, 0x3e, 0x0a, 0x10, 0x4f, 0x74, 0x68, 0x65,
	0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xe8, 0x03, 0x0a, 0x04, 0x53, 0x74, 0x65,
	0x70, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x69,
	0x66, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x66,
	0x75, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1f, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x03, 0x73,
	0x72, 0x63, 0x12, 0x1f, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x03,
	0x64, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x69,
	0x65, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x52, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x72, 0x6f, 0x70, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x72, 0x6f, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x63,
	0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x69, 0x65, 0x63, 0x65, 0x2e, 0x49,
	0x64, 0x52, 0x08, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x64, 0x12, 0x44, 0x0a, 0x0f, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x49,
	0x64, 0x52, 0x0e, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x66, 0x65, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x66, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x53, 0x65, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x68,
	0x69, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x74, 0x68, 0x69, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x63, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f,
	0x74, 0x65, 0x73, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_document_proto_rawDescOnce sync.Once
	file_proto_document_proto_rawDescData = file_proto_document_proto_rawDesc
)

func file_proto_document_proto_rawDescGZIP() []byte {
	file_proto_document_proto_rawDescOnce.Do(func() {
		file_proto_document_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_document_proto_rawDescData)
	})
	return file_proto_document_proto_rawDescData
}

var file_proto_document_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_document_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_document_proto_goTypes = []interface{}{
	(Player_Order)(0),      // 0: document.Player.Order
	(FinishedStatus_Id)(0), // 1: document.FinishedStatus.Id
	(Handicap_Id)(0),       // 2: document.Handicap.Id
	(Piece_Id)(0),          // 3: document.Piece.Id
	(*Player)(nil),         // 4: document.Player
	(*FinishedStatus)(nil), // 5: document.FinishedStatus
	(*Handicap)(nil),       // 6: document.Handicap
	(*Piece)(nil),          // 7: document.Piece
	(*Pos)(nil),            // 8: document.Pos
	(*Kifu)(nil),           // 9: document.Kifu
	(*Step)(nil),           // 10: document.Step
	nil,                    // 11: document.Kifu.OtherFieldsEntry
}
var file_proto_document_proto_depIdxs = []int32{
	0,  // 0: document.Player.order:type_name -> document.Player.Order
	2,  // 1: document.Kifu.handicap:type_name -> document.Handicap.Id
	4,  // 2: document.Kifu.players:type_name -> document.Player
	11, // 3: document.Kifu.other_fields:type_name -> document.Kifu.OtherFieldsEntry
	8,  // 4: document.Step.src:type_name -> document.Pos
	8,  // 5: document.Step.dst:type_name -> document.Pos
	3,  // 6: document.Step.piece:type_name -> document.Piece.Id
	3,  // 7: document.Step.captured:type_name -> document.Piece.Id
	1,  // 8: document.Step.finished_status:type_name -> document.FinishedStatus.Id
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_document_proto_init() }
func file_proto_document_proto_init() {
	if File_proto_document_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_document_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_document_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishedStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_document_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Handicap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_document_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Piece); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_document_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_document_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kifu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_document_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_document_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_document_proto_goTypes,
		DependencyIndexes: file_proto_document_proto_depIdxs,
		EnumInfos:         file_proto_document_proto_enumTypes,
		MessageInfos:      file_proto_document_proto_msgTypes,
	}.Build()
	File_proto_document_proto = out.File
	file_proto_document_proto_rawDesc = nil
	file_proto_document_proto_goTypes = nil
	file_proto_document_proto_depIdxs = nil
}
