// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: proto/kifu.proto

package kifu

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Piece_Id int32

const (
	Piece_NULL      Piece_Id = 0
	Piece_GYOKU     Piece_Id = 1
	Piece_HISHA     Piece_Id = 2
	Piece_RYU       Piece_Id = 3
	Piece_KAKU      Piece_Id = 4
	Piece_UMA       Piece_Id = 5
	Piece_KIN       Piece_Id = 6
	Piece_GIN       Piece_Id = 7
	Piece_NARI_GIN  Piece_Id = 8
	Piece_KEI       Piece_Id = 9
	Piece_NARI_KEI  Piece_Id = 10
	Piece_KYOU      Piece_Id = 11
	Piece_NARI_KYOU Piece_Id = 12
	Piece_FU        Piece_Id = 13
	Piece_TO        Piece_Id = 14
)

// Enum value maps for Piece_Id.
var (
	Piece_Id_name = map[int32]string{
		0:  "NULL",
		1:  "GYOKU",
		2:  "HISHA",
		3:  "RYU",
		4:  "KAKU",
		5:  "UMA",
		6:  "KIN",
		7:  "GIN",
		8:  "NARI_GIN",
		9:  "KEI",
		10: "NARI_KEI",
		11: "KYOU",
		12: "NARI_KYOU",
		13: "FU",
		14: "TO",
	}
	Piece_Id_value = map[string]int32{
		"NULL":      0,
		"GYOKU":     1,
		"HISHA":     2,
		"RYU":       3,
		"KAKU":      4,
		"UMA":       5,
		"KIN":       6,
		"GIN":       7,
		"NARI_GIN":  8,
		"KEI":       9,
		"NARI_KEI":  10,
		"KYOU":      11,
		"NARI_KYOU": 12,
		"FU":        13,
		"TO":        14,
	}
)

func (x Piece_Id) Enum() *Piece_Id {
	p := new(Piece_Id)
	*p = x
	return p
}

func (x Piece_Id) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Piece_Id) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kifu_proto_enumTypes[0].Descriptor()
}

func (Piece_Id) Type() protoreflect.EnumType {
	return &file_proto_kifu_proto_enumTypes[0]
}

func (x Piece_Id) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Piece_Id.Descriptor instead.
func (Piece_Id) EnumDescriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{8, 0}
}

type FinishedStatus_Id int32

const (
	FinishedStatus_NOT_FINISHED    FinishedStatus_Id = 0
	FinishedStatus_SUSPEND         FinishedStatus_Id = 1
	FinishedStatus_SURRENDER       FinishedStatus_Id = 2
	FinishedStatus_DRAW            FinishedStatus_Id = 3
	FinishedStatus_REPETITION_DRAW FinishedStatus_Id = 4
	FinishedStatus_CHECKMATE       FinishedStatus_Id = 5
	FinishedStatus_OVER_TIME_LIMIT FinishedStatus_Id = 6
	FinishedStatus_FOUL_LOSS       FinishedStatus_Id = 7
	FinishedStatus_FOUL_WIN        FinishedStatus_Id = 8
	FinishedStatus_NYUGYOKU_WIN    FinishedStatus_Id = 9
)

// Enum value maps for FinishedStatus_Id.
var (
	FinishedStatus_Id_name = map[int32]string{
		0: "NOT_FINISHED",
		1: "SUSPEND",
		2: "SURRENDER",
		3: "DRAW",
		4: "REPETITION_DRAW",
		5: "CHECKMATE",
		6: "OVER_TIME_LIMIT",
		7: "FOUL_LOSS",
		8: "FOUL_WIN",
		9: "NYUGYOKU_WIN",
	}
	FinishedStatus_Id_value = map[string]int32{
		"NOT_FINISHED":    0,
		"SUSPEND":         1,
		"SURRENDER":       2,
		"DRAW":            3,
		"REPETITION_DRAW": 4,
		"CHECKMATE":       5,
		"OVER_TIME_LIMIT": 6,
		"FOUL_LOSS":       7,
		"FOUL_WIN":        8,
		"NYUGYOKU_WIN":    9,
	}
)

func (x FinishedStatus_Id) Enum() *FinishedStatus_Id {
	p := new(FinishedStatus_Id)
	*p = x
	return p
}

func (x FinishedStatus_Id) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinishedStatus_Id) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kifu_proto_enumTypes[1].Descriptor()
}

func (FinishedStatus_Id) Type() protoreflect.EnumType {
	return &file_proto_kifu_proto_enumTypes[1]
}

func (x FinishedStatus_Id) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinishedStatus_Id.Descriptor instead.
func (FinishedStatus_Id) EnumDescriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{9, 0}
}

type RecentKifuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *RecentKifuRequest) Reset() {
	*x = RecentKifuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecentKifuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentKifuRequest) ProtoMessage() {}

func (x *RecentKifuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentKifuRequest.ProtoReflect.Descriptor instead.
func (*RecentKifuRequest) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{0}
}

func (x *RecentKifuRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecentKifuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kifus []*RecentKifuResponse_Kifu `protobuf:"bytes,1,rep,name=kifus,proto3" json:"kifus,omitempty"`
}

func (x *RecentKifuResponse) Reset() {
	*x = RecentKifuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecentKifuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentKifuResponse) ProtoMessage() {}

func (x *RecentKifuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentKifuResponse.ProtoReflect.Descriptor instead.
func (*RecentKifuResponse) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{1}
}

func (x *RecentKifuResponse) GetKifus() []*RecentKifuResponse_Kifu {
	if x != nil {
		return x.Kifus
	}
	return nil
}

type PostKifuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// required.
	Payload string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// valid values: KIF
	// required.
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// valid values: UTF-8 | Shift_JIS
	// required.
	Encoding string `protobuf:"bytes,3,opt,name=encoding,proto3" json:"encoding,omitempty"`
}

func (x *PostKifuRequest) Reset() {
	*x = PostKifuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostKifuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostKifuRequest) ProtoMessage() {}

func (x *PostKifuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostKifuRequest.ProtoReflect.Descriptor instead.
func (*PostKifuRequest) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{2}
}

func (x *PostKifuRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PostKifuRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PostKifuRequest) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

type PostKifuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KifuId     string                   `protobuf:"bytes,1,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	Duplicated []*PostKifuResponse_Kifu `protobuf:"bytes,2,rep,name=duplicated,proto3" json:"duplicated,omitempty"`
}

func (x *PostKifuResponse) Reset() {
	*x = PostKifuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostKifuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostKifuResponse) ProtoMessage() {}

func (x *PostKifuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostKifuResponse.ProtoReflect.Descriptor instead.
func (*PostKifuResponse) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{3}
}

func (x *PostKifuResponse) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

func (x *PostKifuResponse) GetDuplicated() []*PostKifuResponse_Kifu {
	if x != nil {
		return x.Duplicated
	}
	return nil
}

type DeleteKifuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KifuId string `protobuf:"bytes,1,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
}

func (x *DeleteKifuRequest) Reset() {
	*x = DeleteKifuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKifuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKifuRequest) ProtoMessage() {}

func (x *DeleteKifuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKifuRequest.ProtoReflect.Descriptor instead.
func (*DeleteKifuRequest) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteKifuRequest) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

type DeleteKifuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKifuResponse) Reset() {
	*x = DeleteKifuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKifuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKifuResponse) ProtoMessage() {}

func (x *DeleteKifuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKifuResponse.ProtoReflect.Descriptor instead.
func (*DeleteKifuResponse) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{5}
}

type GetKifuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KifuId string `protobuf:"bytes,1,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
}

func (x *GetKifuRequest) Reset() {
	*x = GetKifuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKifuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKifuRequest) ProtoMessage() {}

func (x *GetKifuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKifuRequest.ProtoReflect.Descriptor instead.
func (*GetKifuRequest) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{6}
}

func (x *GetKifuRequest) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

type Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Pos) Reset() {
	*x = Pos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{7}
}

func (x *Pos) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pos) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Piece struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Piece) Reset() {
	*x = Piece{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Piece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Piece) ProtoMessage() {}

func (x *Piece) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Piece.ProtoReflect.Descriptor instead.
func (*Piece) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{8}
}

type FinishedStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishedStatus) Reset() {
	*x = FinishedStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishedStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishedStatus) ProtoMessage() {}

func (x *FinishedStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishedStatus.ProtoReflect.Descriptor instead.
func (*FinishedStatus) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{9}
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{10}
}

func (x *Value) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Value) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetKifuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string                    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KifuId        string                    `protobuf:"bytes,2,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	StartTs       int64                     `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	EndTs         int64                     `protobuf:"varint,4,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	Handicap      string                    `protobuf:"bytes,5,opt,name=handicap,proto3" json:"handicap,omitempty"`
	GameName      string                    `protobuf:"bytes,6,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	FirstPlayers  []*GetKifuResponse_Player `protobuf:"bytes,7,rep,name=first_players,json=firstPlayers,proto3" json:"first_players,omitempty"`
	SecondPlayers []*GetKifuResponse_Player `protobuf:"bytes,8,rep,name=second_players,json=secondPlayers,proto3" json:"second_players,omitempty"`
	OtherFields   []*Value                  `protobuf:"bytes,9,rep,name=other_fields,json=otherFields,proto3" json:"other_fields,omitempty"`
	Sfen          string                    `protobuf:"bytes,10,opt,name=sfen,proto3" json:"sfen,omitempty"`
	CreatedTs     int64                     `protobuf:"varint,11,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	Steps         []*GetKifuResponse_Step   `protobuf:"bytes,12,rep,name=steps,proto3" json:"steps,omitempty"`
	Note          string                    `protobuf:"bytes,13,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *GetKifuResponse) Reset() {
	*x = GetKifuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKifuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKifuResponse) ProtoMessage() {}

func (x *GetKifuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKifuResponse.ProtoReflect.Descriptor instead.
func (*GetKifuResponse) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{11}
}

func (x *GetKifuResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetKifuResponse) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

func (x *GetKifuResponse) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *GetKifuResponse) GetEndTs() int64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *GetKifuResponse) GetHandicap() string {
	if x != nil {
		return x.Handicap
	}
	return ""
}

func (x *GetKifuResponse) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *GetKifuResponse) GetFirstPlayers() []*GetKifuResponse_Player {
	if x != nil {
		return x.FirstPlayers
	}
	return nil
}

func (x *GetKifuResponse) GetSecondPlayers() []*GetKifuResponse_Player {
	if x != nil {
		return x.SecondPlayers
	}
	return nil
}

func (x *GetKifuResponse) GetOtherFields() []*Value {
	if x != nil {
		return x.OtherFields
	}
	return nil
}

func (x *GetKifuResponse) GetSfen() string {
	if x != nil {
		return x.Sfen
	}
	return ""
}

func (x *GetKifuResponse) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *GetKifuResponse) GetSteps() []*GetKifuResponse_Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *GetKifuResponse) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type GetSamePositionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position       string   `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Steps          int32    `protobuf:"varint,2,opt,name=steps,proto3" json:"steps,omitempty"`
	ExcludeKifuIds []string `protobuf:"bytes,3,rep,name=exclude_kifu_ids,json=excludeKifuIds,proto3" json:"exclude_kifu_ids,omitempty"`
}

func (x *GetSamePositionsRequest) Reset() {
	*x = GetSamePositionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSamePositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSamePositionsRequest) ProtoMessage() {}

func (x *GetSamePositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSamePositionsRequest.ProtoReflect.Descriptor instead.
func (*GetSamePositionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{12}
}

func (x *GetSamePositionsRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *GetSamePositionsRequest) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

func (x *GetSamePositionsRequest) GetExcludeKifuIds() []string {
	if x != nil {
		return x.ExcludeKifuIds
	}
	return nil
}

type GetSamePositionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position string                           `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Kifus    []*GetSamePositionsResponse_Kifu `protobuf:"bytes,2,rep,name=kifus,proto3" json:"kifus,omitempty"`
}

func (x *GetSamePositionsResponse) Reset() {
	*x = GetSamePositionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSamePositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSamePositionsResponse) ProtoMessage() {}

func (x *GetSamePositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSamePositionsResponse.ProtoReflect.Descriptor instead.
func (*GetSamePositionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{13}
}

func (x *GetSamePositionsResponse) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *GetSamePositionsResponse) GetKifus() []*GetSamePositionsResponse_Kifu {
	if x != nil {
		return x.Kifus
	}
	return nil
}

type KifuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to KifuRequestSelect:
	//	*KifuRequest_RequestRecentKifu
	//	*KifuRequest_RequestPostKifu
	//	*KifuRequest_RequestDeleteKifu
	//	*KifuRequest_RequestGetKifu
	//	*KifuRequest_RequestGetSamePositions
	KifuRequestSelect isKifuRequest_KifuRequestSelect `protobuf_oneof:"kifu_request_select"`
}

func (x *KifuRequest) Reset() {
	*x = KifuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KifuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KifuRequest) ProtoMessage() {}

func (x *KifuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KifuRequest.ProtoReflect.Descriptor instead.
func (*KifuRequest) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{14}
}

func (m *KifuRequest) GetKifuRequestSelect() isKifuRequest_KifuRequestSelect {
	if m != nil {
		return m.KifuRequestSelect
	}
	return nil
}

func (x *KifuRequest) GetRequestRecentKifu() *RecentKifuRequest {
	if x, ok := x.GetKifuRequestSelect().(*KifuRequest_RequestRecentKifu); ok {
		return x.RequestRecentKifu
	}
	return nil
}

func (x *KifuRequest) GetRequestPostKifu() *PostKifuRequest {
	if x, ok := x.GetKifuRequestSelect().(*KifuRequest_RequestPostKifu); ok {
		return x.RequestPostKifu
	}
	return nil
}

func (x *KifuRequest) GetRequestDeleteKifu() *DeleteKifuRequest {
	if x, ok := x.GetKifuRequestSelect().(*KifuRequest_RequestDeleteKifu); ok {
		return x.RequestDeleteKifu
	}
	return nil
}

func (x *KifuRequest) GetRequestGetKifu() *GetKifuRequest {
	if x, ok := x.GetKifuRequestSelect().(*KifuRequest_RequestGetKifu); ok {
		return x.RequestGetKifu
	}
	return nil
}

func (x *KifuRequest) GetRequestGetSamePositions() *GetSamePositionsRequest {
	if x, ok := x.GetKifuRequestSelect().(*KifuRequest_RequestGetSamePositions); ok {
		return x.RequestGetSamePositions
	}
	return nil
}

type isKifuRequest_KifuRequestSelect interface {
	isKifuRequest_KifuRequestSelect()
}

type KifuRequest_RequestRecentKifu struct {
	RequestRecentKifu *RecentKifuRequest `protobuf:"bytes,1,opt,name=request_recent_kifu,json=requestRecentKifu,proto3,oneof"`
}

type KifuRequest_RequestPostKifu struct {
	RequestPostKifu *PostKifuRequest `protobuf:"bytes,2,opt,name=request_post_kifu,json=requestPostKifu,proto3,oneof"`
}

type KifuRequest_RequestDeleteKifu struct {
	RequestDeleteKifu *DeleteKifuRequest `protobuf:"bytes,3,opt,name=request_delete_kifu,json=requestDeleteKifu,proto3,oneof"`
}

type KifuRequest_RequestGetKifu struct {
	RequestGetKifu *GetKifuRequest `protobuf:"bytes,4,opt,name=request_get_kifu,json=requestGetKifu,proto3,oneof"`
}

type KifuRequest_RequestGetSamePositions struct {
	RequestGetSamePositions *GetSamePositionsRequest `protobuf:"bytes,5,opt,name=request_get_same_positions,json=requestGetSamePositions,proto3,oneof"`
}

func (*KifuRequest_RequestRecentKifu) isKifuRequest_KifuRequestSelect() {}

func (*KifuRequest_RequestPostKifu) isKifuRequest_KifuRequestSelect() {}

func (*KifuRequest_RequestDeleteKifu) isKifuRequest_KifuRequestSelect() {}

func (*KifuRequest_RequestGetKifu) isKifuRequest_KifuRequestSelect() {}

func (*KifuRequest_RequestGetSamePositions) isKifuRequest_KifuRequestSelect() {}

type KifuResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to KifuResponseSelect:
	//	*KifuResponse_ResponseRecentKifu
	//	*KifuResponse_ResponsePostKifu
	//	*KifuResponse_ResponseDeleteKifu
	//	*KifuResponse_ResponseGetKifu
	//	*KifuResponse_ResponseGetSamePositions
	KifuResponseSelect isKifuResponse_KifuResponseSelect `protobuf_oneof:"kifu_response_select"`
}

func (x *KifuResponse) Reset() {
	*x = KifuResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KifuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KifuResponse) ProtoMessage() {}

func (x *KifuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KifuResponse.ProtoReflect.Descriptor instead.
func (*KifuResponse) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{15}
}

func (m *KifuResponse) GetKifuResponseSelect() isKifuResponse_KifuResponseSelect {
	if m != nil {
		return m.KifuResponseSelect
	}
	return nil
}

func (x *KifuResponse) GetResponseRecentKifu() *RecentKifuResponse {
	if x, ok := x.GetKifuResponseSelect().(*KifuResponse_ResponseRecentKifu); ok {
		return x.ResponseRecentKifu
	}
	return nil
}

func (x *KifuResponse) GetResponsePostKifu() *PostKifuResponse {
	if x, ok := x.GetKifuResponseSelect().(*KifuResponse_ResponsePostKifu); ok {
		return x.ResponsePostKifu
	}
	return nil
}

func (x *KifuResponse) GetResponseDeleteKifu() *DeleteKifuResponse {
	if x, ok := x.GetKifuResponseSelect().(*KifuResponse_ResponseDeleteKifu); ok {
		return x.ResponseDeleteKifu
	}
	return nil
}

func (x *KifuResponse) GetResponseGetKifu() *GetKifuResponse {
	if x, ok := x.GetKifuResponseSelect().(*KifuResponse_ResponseGetKifu); ok {
		return x.ResponseGetKifu
	}
	return nil
}

func (x *KifuResponse) GetResponseGetSamePositions() *GetSamePositionsResponse {
	if x, ok := x.GetKifuResponseSelect().(*KifuResponse_ResponseGetSamePositions); ok {
		return x.ResponseGetSamePositions
	}
	return nil
}

type isKifuResponse_KifuResponseSelect interface {
	isKifuResponse_KifuResponseSelect()
}

type KifuResponse_ResponseRecentKifu struct {
	ResponseRecentKifu *RecentKifuResponse `protobuf:"bytes,1,opt,name=response_recent_kifu,json=responseRecentKifu,proto3,oneof"`
}

type KifuResponse_ResponsePostKifu struct {
	ResponsePostKifu *PostKifuResponse `protobuf:"bytes,2,opt,name=response_post_kifu,json=responsePostKifu,proto3,oneof"`
}

type KifuResponse_ResponseDeleteKifu struct {
	ResponseDeleteKifu *DeleteKifuResponse `protobuf:"bytes,3,opt,name=response_delete_kifu,json=responseDeleteKifu,proto3,oneof"`
}

type KifuResponse_ResponseGetKifu struct {
	ResponseGetKifu *GetKifuResponse `protobuf:"bytes,4,opt,name=response_get_kifu,json=responseGetKifu,proto3,oneof"`
}

type KifuResponse_ResponseGetSamePositions struct {
	ResponseGetSamePositions *GetSamePositionsResponse `protobuf:"bytes,5,opt,name=response_get_same_positions,json=responseGetSamePositions,proto3,oneof"`
}

func (*KifuResponse_ResponseRecentKifu) isKifuResponse_KifuResponseSelect() {}

func (*KifuResponse_ResponsePostKifu) isKifuResponse_KifuResponseSelect() {}

func (*KifuResponse_ResponseDeleteKifu) isKifuResponse_KifuResponseSelect() {}

func (*KifuResponse_ResponseGetKifu) isKifuResponse_KifuResponseSelect() {}

func (*KifuResponse_ResponseGetSamePositions) isKifuResponse_KifuResponseSelect() {}

type RecentKifuResponse_Kifu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KifuId        string   `protobuf:"bytes,2,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	StartTs       int64    `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Handicap      string   `protobuf:"bytes,4,opt,name=handicap,proto3" json:"handicap,omitempty"`
	GameName      string   `protobuf:"bytes,5,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	FirstPlayers  []string `protobuf:"bytes,6,rep,name=first_players,json=firstPlayers,proto3" json:"first_players,omitempty"`
	SecondPlayers []string `protobuf:"bytes,7,rep,name=second_players,json=secondPlayers,proto3" json:"second_players,omitempty"`
	Note          string   `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *RecentKifuResponse_Kifu) Reset() {
	*x = RecentKifuResponse_Kifu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecentKifuResponse_Kifu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentKifuResponse_Kifu) ProtoMessage() {}

func (x *RecentKifuResponse_Kifu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentKifuResponse_Kifu.ProtoReflect.Descriptor instead.
func (*RecentKifuResponse_Kifu) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RecentKifuResponse_Kifu) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecentKifuResponse_Kifu) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

func (x *RecentKifuResponse_Kifu) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *RecentKifuResponse_Kifu) GetHandicap() string {
	if x != nil {
		return x.Handicap
	}
	return ""
}

func (x *RecentKifuResponse_Kifu) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *RecentKifuResponse_Kifu) GetFirstPlayers() []string {
	if x != nil {
		return x.FirstPlayers
	}
	return nil
}

func (x *RecentKifuResponse_Kifu) GetSecondPlayers() []string {
	if x != nil {
		return x.SecondPlayers
	}
	return nil
}

func (x *RecentKifuResponse_Kifu) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type PostKifuResponse_Kifu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KifuId string `protobuf:"bytes,2,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
}

func (x *PostKifuResponse_Kifu) Reset() {
	*x = PostKifuResponse_Kifu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostKifuResponse_Kifu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostKifuResponse_Kifu) ProtoMessage() {}

func (x *PostKifuResponse_Kifu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostKifuResponse_Kifu.ProtoReflect.Descriptor instead.
func (*PostKifuResponse_Kifu) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{3, 0}
}

func (x *PostKifuResponse_Kifu) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostKifuResponse_Kifu) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

type GetKifuResponse_Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Note string `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *GetKifuResponse_Player) Reset() {
	*x = GetKifuResponse_Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKifuResponse_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKifuResponse_Player) ProtoMessage() {}

func (x *GetKifuResponse_Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKifuResponse_Player.ProtoReflect.Descriptor instead.
func (*GetKifuResponse_Player) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetKifuResponse_Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetKifuResponse_Player) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type GetKifuResponse_Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq            int32             `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Position       string            `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Src            *Pos              `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty"`
	Dst            *Pos              `protobuf:"bytes,4,opt,name=dst,proto3" json:"dst,omitempty"`
	Piece          Piece_Id          `protobuf:"varint,5,opt,name=piece,proto3,enum=kifu.Piece_Id" json:"piece,omitempty"`
	FinishedStatus FinishedStatus_Id `protobuf:"varint,6,opt,name=finished_status,json=finishedStatus,proto3,enum=kifu.FinishedStatus_Id" json:"finished_status,omitempty"`
	Promoted       bool              `protobuf:"varint,7,opt,name=promoted,proto3" json:"promoted,omitempty"`
	Captured       Piece_Id          `protobuf:"varint,8,opt,name=captured,proto3,enum=kifu.Piece_Id" json:"captured,omitempty"`
	TimestampSec   int32             `protobuf:"varint,9,opt,name=timestamp_sec,json=timestampSec,proto3" json:"timestamp_sec,omitempty"`
	ThinkingSec    int32             `protobuf:"varint,10,opt,name=thinking_sec,json=thinkingSec,proto3" json:"thinking_sec,omitempty"`
	Notes          []string          `protobuf:"bytes,11,rep,name=notes,proto3" json:"notes,omitempty"`
}

func (x *GetKifuResponse_Step) Reset() {
	*x = GetKifuResponse_Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKifuResponse_Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKifuResponse_Step) ProtoMessage() {}

func (x *GetKifuResponse_Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKifuResponse_Step.ProtoReflect.Descriptor instead.
func (*GetKifuResponse_Step) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{11, 1}
}

func (x *GetKifuResponse_Step) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetKifuResponse_Step) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *GetKifuResponse_Step) GetSrc() *Pos {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *GetKifuResponse_Step) GetDst() *Pos {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *GetKifuResponse_Step) GetPiece() Piece_Id {
	if x != nil {
		return x.Piece
	}
	return Piece_NULL
}

func (x *GetKifuResponse_Step) GetFinishedStatus() FinishedStatus_Id {
	if x != nil {
		return x.FinishedStatus
	}
	return FinishedStatus_NOT_FINISHED
}

func (x *GetKifuResponse_Step) GetPromoted() bool {
	if x != nil {
		return x.Promoted
	}
	return false
}

func (x *GetKifuResponse_Step) GetCaptured() Piece_Id {
	if x != nil {
		return x.Captured
	}
	return Piece_NULL
}

func (x *GetKifuResponse_Step) GetTimestampSec() int32 {
	if x != nil {
		return x.TimestampSec
	}
	return 0
}

func (x *GetKifuResponse_Step) GetThinkingSec() int32 {
	if x != nil {
		return x.ThinkingSec
	}
	return 0
}

func (x *GetKifuResponse_Step) GetNotes() []string {
	if x != nil {
		return x.Notes
	}
	return nil
}

type GetSamePositionsResponse_Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq            int32             `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Src            *Pos              `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst            *Pos              `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Piece          Piece_Id          `protobuf:"varint,4,opt,name=piece,proto3,enum=kifu.Piece_Id" json:"piece,omitempty"`
	Promoted       bool              `protobuf:"varint,5,opt,name=promoted,proto3" json:"promoted,omitempty"`
	FinishedStatus FinishedStatus_Id `protobuf:"varint,6,opt,name=finished_status,json=finishedStatus,proto3,enum=kifu.FinishedStatus_Id" json:"finished_status,omitempty"`
}

func (x *GetSamePositionsResponse_Step) Reset() {
	*x = GetSamePositionsResponse_Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSamePositionsResponse_Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSamePositionsResponse_Step) ProtoMessage() {}

func (x *GetSamePositionsResponse_Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSamePositionsResponse_Step.ProtoReflect.Descriptor instead.
func (*GetSamePositionsResponse_Step) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{13, 0}
}

func (x *GetSamePositionsResponse_Step) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetSamePositionsResponse_Step) GetSrc() *Pos {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *GetSamePositionsResponse_Step) GetDst() *Pos {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *GetSamePositionsResponse_Step) GetPiece() Piece_Id {
	if x != nil {
		return x.Piece
	}
	return Piece_NULL
}

func (x *GetSamePositionsResponse_Step) GetPromoted() bool {
	if x != nil {
		return x.Promoted
	}
	return false
}

func (x *GetSamePositionsResponse_Step) GetFinishedStatus() FinishedStatus_Id {
	if x != nil {
		return x.FinishedStatus
	}
	return FinishedStatus_NOT_FINISHED
}

type GetSamePositionsResponse_Kifu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string                           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KifuId string                           `protobuf:"bytes,2,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	Seq    int32                            `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Steps  []*GetSamePositionsResponse_Step `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
}

func (x *GetSamePositionsResponse_Kifu) Reset() {
	*x = GetSamePositionsResponse_Kifu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kifu_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSamePositionsResponse_Kifu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSamePositionsResponse_Kifu) ProtoMessage() {}

func (x *GetSamePositionsResponse_Kifu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kifu_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSamePositionsResponse_Kifu.ProtoReflect.Descriptor instead.
func (*GetSamePositionsResponse_Kifu) Descriptor() ([]byte, []int) {
	return file_proto_kifu_proto_rawDescGZIP(), []int{13, 1}
}

func (x *GetSamePositionsResponse_Kifu) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSamePositionsResponse_Kifu) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

func (x *GetSamePositionsResponse_Kifu) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetSamePositionsResponse_Kifu) GetSteps() []*GetSamePositionsResponse_Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

var File_proto_kifu_proto protoreflect.FileDescriptor

var file_proto_kifu_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6b, 0x69, 0x66, 0x75, 0x22, 0x29, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x65,
	0x6e, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0xb8, 0x02, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4b, 0x69,
	0x66, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x6b, 0x69,
	0x66, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x69, 0x66, 0x75,
	0x2e, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x05, 0x6b, 0x69, 0x66, 0x75, 0x73, 0x1a,
	0xec, 0x01, 0x0a, 0x04, 0x4b, 0x69, 0x66, 0x75, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x66, 0x75, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x63, 0x61,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x63, 0x61,
	0x70, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x69, 0x72, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0x5f,
	0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x22,
	0xa2, 0x01, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x66, 0x75, 0x49, 0x64, 0x12, 0x3b, 0x0a,
	0x0a, 0x64, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66,
	0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x0a,
	0x64, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x1a, 0x38, 0x0a, 0x04, 0x4b, 0x69,
	0x66, 0x75, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b,
	0x69, 0x66, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x69,
	0x66, 0x75, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69,
	0x66, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x69, 0x66,
	0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x66, 0x75,
	0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x66, 0x75,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x29, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4b,
	0x69, 0x66, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x69,
	0x66, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x66,
	0x75, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0xaa, 0x01, 0x0a, 0x05, 0x50, 0x69, 0x65, 0x63, 0x65,
	0x22, 0xa0, 0x01, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x59, 0x4f, 0x4b, 0x55, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x48, 0x49, 0x53, 0x48, 0x41, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x59, 0x55, 0x10, 0x03,
	0x12, 0x08, 0x0a, 0x04, 0x4b, 0x41, 0x4b, 0x55, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x4d,
	0x41, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x4b, 0x49, 0x4e, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03,
	0x47, 0x49, 0x4e, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x41, 0x52, 0x49, 0x5f, 0x47, 0x49,
	0x4e, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x4b, 0x45, 0x49, 0x10, 0x09, 0x12, 0x0c, 0x0a, 0x08,
	0x4e, 0x41, 0x52, 0x49, 0x5f, 0x4b, 0x45, 0x49, 0x10, 0x0a, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x59,
	0x4f, 0x55, 0x10, 0x0b, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x41, 0x52, 0x49, 0x5f, 0x4b, 0x59, 0x4f,
	0x55, 0x10, 0x0c, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x55, 0x10, 0x0d, 0x12, 0x06, 0x0a, 0x02, 0x54,
	0x4f, 0x10, 0x0e, 0x22, 0xb7, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x0c, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x55, 0x53, 0x50, 0x45, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x44,
	0x52, 0x41, 0x57, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x50, 0x45, 0x54, 0x49, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x52, 0x41, 0x57, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x48,
	0x45, 0x43, 0x4b, 0x4d, 0x41, 0x54, 0x45, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x56, 0x45,
	0x52, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x06, 0x12, 0x0d,
	0x0a, 0x09, 0x46, 0x4f, 0x55, 0x4c, 0x5f, 0x4c, 0x4f, 0x53, 0x53, 0x10, 0x07, 0x12, 0x0c, 0x0a,
	0x08, 0x46, 0x4f, 0x55, 0x4c, 0x5f, 0x57, 0x49, 0x4e, 0x10, 0x08, 0x12, 0x10, 0x0a, 0x0c, 0x4e,
	0x59, 0x55, 0x47, 0x59, 0x4f, 0x4b, 0x55, 0x5f, 0x57, 0x49, 0x4e, 0x10, 0x09, 0x22, 0x31, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x90, 0x07, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6b, 0x69, 0x66, 0x75, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x73, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x54, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x61, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x41, 0x0a, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e,
	0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0c, 0x66, 0x69, 0x72, 0x73, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x12, 0x43, 0x0a, 0x0e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b,
	0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0d, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x2e, 0x0a, 0x0c, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0b, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x66, 0x65,
	0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x66, 0x65, 0x6e, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x73, 0x12, 0x30, 0x0a, 0x05,
	0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6b, 0x69,
	0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x1a, 0x30, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x6f, 0x74, 0x65, 0x1a, 0xfc, 0x02, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x03, 0x73,
	0x72, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e,
	0x50, 0x6f, 0x73, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x1b, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50, 0x6f, 0x73,
	0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50, 0x69, 0x65, 0x63,
	0x65, 0x2e, 0x49, 0x64, 0x52, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x49, 0x64, 0x52, 0x0e, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x63, 0x61, 0x70,
	0x74, 0x75, 0x72, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6b, 0x69,
	0x66, 0x75, 0x2e, 0x50, 0x69, 0x65, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x52, 0x08, 0x63, 0x61, 0x70,
	0x74, 0x75, 0x72, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x53, 0x65, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x68,
	0x69, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x74, 0x68, 0x69, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x63, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f,
	0x74, 0x65, 0x73, 0x22, 0x75, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x65, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73,
	0x12, 0x28, 0x0a, 0x10, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x6b, 0x69, 0x66, 0x75,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x78, 0x63, 0x6c,
	0x75, 0x64, 0x65, 0x4b, 0x69, 0x66, 0x75, 0x49, 0x64, 0x73, 0x22, 0xd2, 0x03, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x05, 0x6b, 0x69, 0x66, 0x75, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d,
	0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x05, 0x6b, 0x69, 0x66, 0x75, 0x73, 0x1a, 0xd6,
	0x01, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x03, 0x73, 0x72, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50, 0x6f,
	0x73, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x1b, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x03,
	0x64, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50, 0x69, 0x65, 0x63, 0x65, 0x2e,
	0x49, 0x64, 0x52, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x65, 0x64, 0x12, 0x40, 0x0a, 0x0f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x49, 0x64, 0x52, 0x0e, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x85, 0x01, 0x0a, 0x04, 0x4b, 0x69, 0x66, 0x75,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x69, 0x66,
	0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x66, 0x75,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x73, 0x65, 0x71, 0x12, 0x39, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61,
	0x6d, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x22,
	0x9f, 0x03, 0x0a, 0x0b, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x49, 0x0a, 0x13, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x6e,
	0x74, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6b,
	0x69, 0x66, 0x75, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x11, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x12, 0x43, 0x0a, 0x11, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x12,
	0x49, 0x0a, 0x13, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6b,
	0x69, 0x66, 0x75, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x11, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x66, 0x75, 0x12, 0x40, 0x0a, 0x10, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x4b,
	0x69, 0x66, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x12, 0x5c, 0x0a, 0x1a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x61, 0x6d, 0x65,
	0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x17, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d,
	0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x15, 0x0a, 0x13, 0x6b, 0x69,
	0x66, 0x75, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x22, 0xb0, 0x03, 0x0a, 0x0c, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4c, 0x0a, 0x14, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x72,
	0x65, 0x63, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4b, 0x69,
	0x66, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x12, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x66, 0x75,
	0x12, 0x46, 0x0a, 0x12, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x70, 0x6f, 0x73,
	0x74, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6b,
	0x69, 0x66, 0x75, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x10, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x12, 0x4c, 0x0a, 0x14, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6b, 0x69, 0x66, 0x75,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x12, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4b, 0x69, 0x66, 0x75, 0x12, 0x43, 0x0a, 0x11, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x12, 0x5f, 0x0a, 0x1b, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x61, 0x6d, 0x65,
	0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x18, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x53,
	0x61, 0x6d, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x16, 0x0a, 0x14,
	0x6b, 0x69, 0x66, 0x75, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x69,
	0x66, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_kifu_proto_rawDescOnce sync.Once
	file_proto_kifu_proto_rawDescData = file_proto_kifu_proto_rawDesc
)

func file_proto_kifu_proto_rawDescGZIP() []byte {
	file_proto_kifu_proto_rawDescOnce.Do(func() {
		file_proto_kifu_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_kifu_proto_rawDescData)
	})
	return file_proto_kifu_proto_rawDescData
}

var file_proto_kifu_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_kifu_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_kifu_proto_goTypes = []interface{}{
	(Piece_Id)(0),                         // 0: kifu.Piece.Id
	(FinishedStatus_Id)(0),                // 1: kifu.FinishedStatus.Id
	(*RecentKifuRequest)(nil),             // 2: kifu.RecentKifuRequest
	(*RecentKifuResponse)(nil),            // 3: kifu.RecentKifuResponse
	(*PostKifuRequest)(nil),               // 4: kifu.PostKifuRequest
	(*PostKifuResponse)(nil),              // 5: kifu.PostKifuResponse
	(*DeleteKifuRequest)(nil),             // 6: kifu.DeleteKifuRequest
	(*DeleteKifuResponse)(nil),            // 7: kifu.DeleteKifuResponse
	(*GetKifuRequest)(nil),                // 8: kifu.GetKifuRequest
	(*Pos)(nil),                           // 9: kifu.Pos
	(*Piece)(nil),                         // 10: kifu.Piece
	(*FinishedStatus)(nil),                // 11: kifu.FinishedStatus
	(*Value)(nil),                         // 12: kifu.Value
	(*GetKifuResponse)(nil),               // 13: kifu.GetKifuResponse
	(*GetSamePositionsRequest)(nil),       // 14: kifu.GetSamePositionsRequest
	(*GetSamePositionsResponse)(nil),      // 15: kifu.GetSamePositionsResponse
	(*KifuRequest)(nil),                   // 16: kifu.KifuRequest
	(*KifuResponse)(nil),                  // 17: kifu.KifuResponse
	(*RecentKifuResponse_Kifu)(nil),       // 18: kifu.RecentKifuResponse.Kifu
	(*PostKifuResponse_Kifu)(nil),         // 19: kifu.PostKifuResponse.Kifu
	(*GetKifuResponse_Player)(nil),        // 20: kifu.GetKifuResponse.Player
	(*GetKifuResponse_Step)(nil),          // 21: kifu.GetKifuResponse.Step
	(*GetSamePositionsResponse_Step)(nil), // 22: kifu.GetSamePositionsResponse.Step
	(*GetSamePositionsResponse_Kifu)(nil), // 23: kifu.GetSamePositionsResponse.Kifu
}
var file_proto_kifu_proto_depIdxs = []int32{
	18, // 0: kifu.RecentKifuResponse.kifus:type_name -> kifu.RecentKifuResponse.Kifu
	19, // 1: kifu.PostKifuResponse.duplicated:type_name -> kifu.PostKifuResponse.Kifu
	20, // 2: kifu.GetKifuResponse.first_players:type_name -> kifu.GetKifuResponse.Player
	20, // 3: kifu.GetKifuResponse.second_players:type_name -> kifu.GetKifuResponse.Player
	12, // 4: kifu.GetKifuResponse.other_fields:type_name -> kifu.Value
	21, // 5: kifu.GetKifuResponse.steps:type_name -> kifu.GetKifuResponse.Step
	23, // 6: kifu.GetSamePositionsResponse.kifus:type_name -> kifu.GetSamePositionsResponse.Kifu
	2,  // 7: kifu.KifuRequest.request_recent_kifu:type_name -> kifu.RecentKifuRequest
	4,  // 8: kifu.KifuRequest.request_post_kifu:type_name -> kifu.PostKifuRequest
	6,  // 9: kifu.KifuRequest.request_delete_kifu:type_name -> kifu.DeleteKifuRequest
	8,  // 10: kifu.KifuRequest.request_get_kifu:type_name -> kifu.GetKifuRequest
	14, // 11: kifu.KifuRequest.request_get_same_positions:type_name -> kifu.GetSamePositionsRequest
	3,  // 12: kifu.KifuResponse.response_recent_kifu:type_name -> kifu.RecentKifuResponse
	5,  // 13: kifu.KifuResponse.response_post_kifu:type_name -> kifu.PostKifuResponse
	7,  // 14: kifu.KifuResponse.response_delete_kifu:type_name -> kifu.DeleteKifuResponse
	13, // 15: kifu.KifuResponse.response_get_kifu:type_name -> kifu.GetKifuResponse
	15, // 16: kifu.KifuResponse.response_get_same_positions:type_name -> kifu.GetSamePositionsResponse
	9,  // 17: kifu.GetKifuResponse.Step.src:type_name -> kifu.Pos
	9,  // 18: kifu.GetKifuResponse.Step.dst:type_name -> kifu.Pos
	0,  // 19: kifu.GetKifuResponse.Step.piece:type_name -> kifu.Piece.Id
	1,  // 20: kifu.GetKifuResponse.Step.finished_status:type_name -> kifu.FinishedStatus.Id
	0,  // 21: kifu.GetKifuResponse.Step.captured:type_name -> kifu.Piece.Id
	9,  // 22: kifu.GetSamePositionsResponse.Step.src:type_name -> kifu.Pos
	9,  // 23: kifu.GetSamePositionsResponse.Step.dst:type_name -> kifu.Pos
	0,  // 24: kifu.GetSamePositionsResponse.Step.piece:type_name -> kifu.Piece.Id
	1,  // 25: kifu.GetSamePositionsResponse.Step.finished_status:type_name -> kifu.FinishedStatus.Id
	22, // 26: kifu.GetSamePositionsResponse.Kifu.steps:type_name -> kifu.GetSamePositionsResponse.Step
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_proto_kifu_proto_init() }
func file_proto_kifu_proto_init() {
	if File_proto_kifu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_kifu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecentKifuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecentKifuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostKifuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostKifuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKifuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKifuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKifuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Piece); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishedStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKifuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSamePositionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSamePositionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KifuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KifuResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecentKifuResponse_Kifu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostKifuResponse_Kifu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKifuResponse_Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKifuResponse_Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSamePositionsResponse_Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kifu_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSamePositionsResponse_Kifu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_kifu_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*KifuRequest_RequestRecentKifu)(nil),
		(*KifuRequest_RequestPostKifu)(nil),
		(*KifuRequest_RequestDeleteKifu)(nil),
		(*KifuRequest_RequestGetKifu)(nil),
		(*KifuRequest_RequestGetSamePositions)(nil),
	}
	file_proto_kifu_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*KifuResponse_ResponseRecentKifu)(nil),
		(*KifuResponse_ResponsePostKifu)(nil),
		(*KifuResponse_ResponseDeleteKifu)(nil),
		(*KifuResponse_ResponseGetKifu)(nil),
		(*KifuResponse_ResponseGetSamePositions)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_kifu_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_kifu_proto_goTypes,
		DependencyIndexes: file_proto_kifu_proto_depIdxs,
		EnumInfos:         file_proto_kifu_proto_enumTypes,
		MessageInfos:      file_proto_kifu_proto_msgTypes,
	}.Build()
	File_proto_kifu_proto = out.File
	file_proto_kifu_proto_rawDesc = nil
	file_proto_kifu_proto_goTypes = nil
	file_proto_kifu_proto_depIdxs = nil
}
