version: 0.2

env:
  parameter-store:
    SITE_DOMAIN_NAME: /kansousen/prod/siteDomainName
    AUTH_DOMAIN_NAME: /kansousen/prod/authDomainName
    USER_POOL_CLIENT_ID: /kansousen/prod/userPoolClientId

phases:
  install:
    commands:
      - npm install -g uglify-js

  pre_build:
    commands:
      - sam --version
      - elm --version

  build:
    commands:
      - sam build
      - cp -r static public
      - elm make src/Main.elm --output=static/main.opt.js --optimize
      - uglifyjs --compress --mangle -- static/main.opt.js > public/main.js
      - jq --null-input --monochrome-output --compact-output --arg host https://$SITE_DOMAIN_NAME/ --arg clientId $USER_POOL_CLIENT_ID --arg idp https://$AUTH_DOMAIN_NAME/ '{Host:$host,UserPoolClientID:$clientId,IDP:$idp}' > public/config.json

artifacts:
  files:
    - '**/*'
