// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: proto/lambdakifu.proto

package lambdakifu

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Piece_Id int32

const (
	Piece_NULL      Piece_Id = 0
	Piece_GYOKU     Piece_Id = 1
	Piece_HISHA     Piece_Id = 2
	Piece_RYU       Piece_Id = 3
	Piece_KAKU      Piece_Id = 4
	Piece_UMA       Piece_Id = 5
	Piece_KIN       Piece_Id = 6
	Piece_GIN       Piece_Id = 7
	Piece_NARI_GIN  Piece_Id = 8
	Piece_KEI       Piece_Id = 9
	Piece_NARI_KEI  Piece_Id = 10
	Piece_KYOU      Piece_Id = 11
	Piece_NARI_KYOU Piece_Id = 12
	Piece_FU        Piece_Id = 13
	Piece_TO        Piece_Id = 14
)

// Enum value maps for Piece_Id.
var (
	Piece_Id_name = map[int32]string{
		0:  "NULL",
		1:  "GYOKU",
		2:  "HISHA",
		3:  "RYU",
		4:  "KAKU",
		5:  "UMA",
		6:  "KIN",
		7:  "GIN",
		8:  "NARI_GIN",
		9:  "KEI",
		10: "NARI_KEI",
		11: "KYOU",
		12: "NARI_KYOU",
		13: "FU",
		14: "TO",
	}
	Piece_Id_value = map[string]int32{
		"NULL":      0,
		"GYOKU":     1,
		"HISHA":     2,
		"RYU":       3,
		"KAKU":      4,
		"UMA":       5,
		"KIN":       6,
		"GIN":       7,
		"NARI_GIN":  8,
		"KEI":       9,
		"NARI_KEI":  10,
		"KYOU":      11,
		"NARI_KYOU": 12,
		"FU":        13,
		"TO":        14,
	}
)

func (x Piece_Id) Enum() *Piece_Id {
	p := new(Piece_Id)
	*p = x
	return p
}

func (x Piece_Id) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Piece_Id) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lambdakifu_proto_enumTypes[0].Descriptor()
}

func (Piece_Id) Type() protoreflect.EnumType {
	return &file_proto_lambdakifu_proto_enumTypes[0]
}

func (x Piece_Id) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Piece_Id.Descriptor instead.
func (Piece_Id) EnumDescriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{2, 0}
}

type FinishedStatus_Id int32

const (
	FinishedStatus_NOT_FINISHED    FinishedStatus_Id = 0
	FinishedStatus_SUSPEND         FinishedStatus_Id = 1
	FinishedStatus_SURRENDER       FinishedStatus_Id = 2
	FinishedStatus_DRAW            FinishedStatus_Id = 3
	FinishedStatus_REPETITION_DRAW FinishedStatus_Id = 4
	FinishedStatus_CHECKMATE       FinishedStatus_Id = 5
	FinishedStatus_OVER_TIME_LIMIT FinishedStatus_Id = 6
	FinishedStatus_FOUL_LOSS       FinishedStatus_Id = 7
	FinishedStatus_FOUL_WIN        FinishedStatus_Id = 8
	FinishedStatus_NYUGYOKU_WIN    FinishedStatus_Id = 9
)

// Enum value maps for FinishedStatus_Id.
var (
	FinishedStatus_Id_name = map[int32]string{
		0: "NOT_FINISHED",
		1: "SUSPEND",
		2: "SURRENDER",
		3: "DRAW",
		4: "REPETITION_DRAW",
		5: "CHECKMATE",
		6: "OVER_TIME_LIMIT",
		7: "FOUL_LOSS",
		8: "FOUL_WIN",
		9: "NYUGYOKU_WIN",
	}
	FinishedStatus_Id_value = map[string]int32{
		"NOT_FINISHED":    0,
		"SUSPEND":         1,
		"SURRENDER":       2,
		"DRAW":            3,
		"REPETITION_DRAW": 4,
		"CHECKMATE":       5,
		"OVER_TIME_LIMIT": 6,
		"FOUL_LOSS":       7,
		"FOUL_WIN":        8,
		"NYUGYOKU_WIN":    9,
	}
)

func (x FinishedStatus_Id) Enum() *FinishedStatus_Id {
	p := new(FinishedStatus_Id)
	*p = x
	return p
}

func (x FinishedStatus_Id) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinishedStatus_Id) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lambdakifu_proto_enumTypes[1].Descriptor()
}

func (FinishedStatus_Id) Type() protoreflect.EnumType {
	return &file_proto_lambdakifu_proto_enumTypes[1]
}

func (x FinishedStatus_Id) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinishedStatus_Id.Descriptor instead.
func (FinishedStatus_Id) EnumDescriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{3, 0}
}

type PostKifuInput_Format int32

const (
	PostKifuInput_KIF PostKifuInput_Format = 0
)

// Enum value maps for PostKifuInput_Format.
var (
	PostKifuInput_Format_name = map[int32]string{
		0: "KIF",
	}
	PostKifuInput_Format_value = map[string]int32{
		"KIF": 0,
	}
)

func (x PostKifuInput_Format) Enum() *PostKifuInput_Format {
	p := new(PostKifuInput_Format)
	*p = x
	return p
}

func (x PostKifuInput_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostKifuInput_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lambdakifu_proto_enumTypes[2].Descriptor()
}

func (PostKifuInput_Format) Type() protoreflect.EnumType {
	return &file_proto_lambdakifu_proto_enumTypes[2]
}

func (x PostKifuInput_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostKifuInput_Format.Descriptor instead.
func (PostKifuInput_Format) EnumDescriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{8, 0}
}

type PostKifuInput_Encoding int32

const (
	PostKifuInput_UTF8      PostKifuInput_Encoding = 0
	PostKifuInput_SHIFT_JIS PostKifuInput_Encoding = 1
)

// Enum value maps for PostKifuInput_Encoding.
var (
	PostKifuInput_Encoding_name = map[int32]string{
		0: "UTF8",
		1: "SHIFT_JIS",
	}
	PostKifuInput_Encoding_value = map[string]int32{
		"UTF8":      0,
		"SHIFT_JIS": 1,
	}
)

func (x PostKifuInput_Encoding) Enum() *PostKifuInput_Encoding {
	p := new(PostKifuInput_Encoding)
	*p = x
	return p
}

func (x PostKifuInput_Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostKifuInput_Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lambdakifu_proto_enumTypes[3].Descriptor()
}

func (PostKifuInput_Encoding) Type() protoreflect.EnumType {
	return &file_proto_lambdakifu_proto_enumTypes[3]
}

func (x PostKifuInput_Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostKifuInput_Encoding.Descriptor instead.
func (PostKifuInput_Encoding) EnumDescriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{8, 1}
}

type GetKifuInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KifuId string `protobuf:"bytes,2,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
}

func (x *GetKifuInput) Reset() {
	*x = GetKifuInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKifuInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKifuInput) ProtoMessage() {}

func (x *GetKifuInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKifuInput.ProtoReflect.Descriptor instead.
func (*GetKifuInput) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{0}
}

func (x *GetKifuInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetKifuInput) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

type Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Pos) Reset() {
	*x = Pos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{1}
}

func (x *Pos) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pos) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Piece struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Piece) Reset() {
	*x = Piece{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Piece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Piece) ProtoMessage() {}

func (x *Piece) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Piece.ProtoReflect.Descriptor instead.
func (*Piece) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{2}
}

type FinishedStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishedStatus) Reset() {
	*x = FinishedStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishedStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishedStatus) ProtoMessage() {}

func (x *FinishedStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishedStatus.ProtoReflect.Descriptor instead.
func (*FinishedStatus) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{3}
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{4}
}

func (x *Value) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Value) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetKifuOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KifuId        string                  `protobuf:"bytes,2,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	StartTs       int64                   `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	EndTs         int64                   `protobuf:"varint,4,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	Handicap      string                  `protobuf:"bytes,5,opt,name=handicap,proto3" json:"handicap,omitempty"`
	GameName      string                  `protobuf:"bytes,6,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	FirstPlayers  []*GetKifuOutput_Player `protobuf:"bytes,7,rep,name=first_players,json=firstPlayers,proto3" json:"first_players,omitempty"`
	SecondPlayers []*GetKifuOutput_Player `protobuf:"bytes,8,rep,name=second_players,json=secondPlayers,proto3" json:"second_players,omitempty"`
	OtherFields   []*Value                `protobuf:"bytes,9,rep,name=other_fields,json=otherFields,proto3" json:"other_fields,omitempty"`
	Sfen          string                  `protobuf:"bytes,10,opt,name=sfen,proto3" json:"sfen,omitempty"`
	CreatedTs     int64                   `protobuf:"varint,11,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	Steps         []*GetKifuOutput_Step   `protobuf:"bytes,12,rep,name=steps,proto3" json:"steps,omitempty"`
	Note          string                  `protobuf:"bytes,13,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *GetKifuOutput) Reset() {
	*x = GetKifuOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKifuOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKifuOutput) ProtoMessage() {}

func (x *GetKifuOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKifuOutput.ProtoReflect.Descriptor instead.
func (*GetKifuOutput) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{5}
}

func (x *GetKifuOutput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetKifuOutput) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

func (x *GetKifuOutput) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *GetKifuOutput) GetEndTs() int64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *GetKifuOutput) GetHandicap() string {
	if x != nil {
		return x.Handicap
	}
	return ""
}

func (x *GetKifuOutput) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *GetKifuOutput) GetFirstPlayers() []*GetKifuOutput_Player {
	if x != nil {
		return x.FirstPlayers
	}
	return nil
}

func (x *GetKifuOutput) GetSecondPlayers() []*GetKifuOutput_Player {
	if x != nil {
		return x.SecondPlayers
	}
	return nil
}

func (x *GetKifuOutput) GetOtherFields() []*Value {
	if x != nil {
		return x.OtherFields
	}
	return nil
}

func (x *GetKifuOutput) GetSfen() string {
	if x != nil {
		return x.Sfen
	}
	return ""
}

func (x *GetKifuOutput) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *GetKifuOutput) GetSteps() []*GetKifuOutput_Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *GetKifuOutput) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type RecentKifuInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *RecentKifuInput) Reset() {
	*x = RecentKifuInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecentKifuInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentKifuInput) ProtoMessage() {}

func (x *RecentKifuInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentKifuInput.ProtoReflect.Descriptor instead.
func (*RecentKifuInput) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{6}
}

func (x *RecentKifuInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecentKifuInput) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecentKifuOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kifus []*RecentKifuOutput_Kifu `protobuf:"bytes,1,rep,name=kifus,proto3" json:"kifus,omitempty"`
}

func (x *RecentKifuOutput) Reset() {
	*x = RecentKifuOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecentKifuOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentKifuOutput) ProtoMessage() {}

func (x *RecentKifuOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentKifuOutput.ProtoReflect.Descriptor instead.
func (*RecentKifuOutput) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{7}
}

func (x *RecentKifuOutput) GetKifus() []*RecentKifuOutput_Kifu {
	if x != nil {
		return x.Kifus
	}
	return nil
}

type PostKifuInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Payload  string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Format   PostKifuInput_Format   `protobuf:"varint,3,opt,name=format,proto3,enum=lambdakifu.PostKifuInput_Format" json:"format,omitempty"`
	Encoding PostKifuInput_Encoding `protobuf:"varint,4,opt,name=encoding,proto3,enum=lambdakifu.PostKifuInput_Encoding" json:"encoding,omitempty"`
}

func (x *PostKifuInput) Reset() {
	*x = PostKifuInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostKifuInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostKifuInput) ProtoMessage() {}

func (x *PostKifuInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostKifuInput.ProtoReflect.Descriptor instead.
func (*PostKifuInput) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{8}
}

func (x *PostKifuInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostKifuInput) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PostKifuInput) GetFormat() PostKifuInput_Format {
	if x != nil {
		return x.Format
	}
	return PostKifuInput_KIF
}

func (x *PostKifuInput) GetEncoding() PostKifuInput_Encoding {
	if x != nil {
		return x.Encoding
	}
	return PostKifuInput_UTF8
}

type PostKifuOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KifuId string `protobuf:"bytes,1,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
}

func (x *PostKifuOutput) Reset() {
	*x = PostKifuOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostKifuOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostKifuOutput) ProtoMessage() {}

func (x *PostKifuOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostKifuOutput.ProtoReflect.Descriptor instead.
func (*PostKifuOutput) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{9}
}

func (x *PostKifuOutput) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

type DeleteKifuInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KifuId string `protobuf:"bytes,2,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
}

func (x *DeleteKifuInput) Reset() {
	*x = DeleteKifuInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKifuInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKifuInput) ProtoMessage() {}

func (x *DeleteKifuInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKifuInput.ProtoReflect.Descriptor instead.
func (*DeleteKifuInput) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteKifuInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteKifuInput) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

type DeleteKifuOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKifuOutput) Reset() {
	*x = DeleteKifuOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKifuOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKifuOutput) ProtoMessage() {}

func (x *DeleteKifuOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKifuOutput.ProtoReflect.Descriptor instead.
func (*DeleteKifuOutput) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{11}
}

type GetSamePositionsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Position       string   `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Steps          int32    `protobuf:"varint,3,opt,name=steps,proto3" json:"steps,omitempty"`
	ExcludeKifuIds []string `protobuf:"bytes,4,rep,name=exclude_kifu_ids,json=excludeKifuIds,proto3" json:"exclude_kifu_ids,omitempty"`
}

func (x *GetSamePositionsInput) Reset() {
	*x = GetSamePositionsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSamePositionsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSamePositionsInput) ProtoMessage() {}

func (x *GetSamePositionsInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSamePositionsInput.ProtoReflect.Descriptor instead.
func (*GetSamePositionsInput) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{12}
}

func (x *GetSamePositionsInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSamePositionsInput) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *GetSamePositionsInput) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

func (x *GetSamePositionsInput) GetExcludeKifuIds() []string {
	if x != nil {
		return x.ExcludeKifuIds
	}
	return nil
}

type GetSamePositionsOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position string                          `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Phases   []*GetSamePositionsOutput_Phase `protobuf:"bytes,2,rep,name=phases,proto3" json:"phases,omitempty"`
}

func (x *GetSamePositionsOutput) Reset() {
	*x = GetSamePositionsOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSamePositionsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSamePositionsOutput) ProtoMessage() {}

func (x *GetSamePositionsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSamePositionsOutput.ProtoReflect.Descriptor instead.
func (*GetSamePositionsOutput) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{13}
}

func (x *GetSamePositionsOutput) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *GetSamePositionsOutput) GetPhases() []*GetSamePositionsOutput_Phase {
	if x != nil {
		return x.Phases
	}
	return nil
}

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Select:
	//	*Input_RecentKifuInput
	//	*Input_PostKifuInput
	//	*Input_DeleteKifuInput
	//	*Input_GetKifuInput
	//	*Input_GetSamePositionsInput
	Select isInput_Select `protobuf_oneof:"select"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{14}
}

func (m *Input) GetSelect() isInput_Select {
	if m != nil {
		return m.Select
	}
	return nil
}

func (x *Input) GetRecentKifuInput() *RecentKifuInput {
	if x, ok := x.GetSelect().(*Input_RecentKifuInput); ok {
		return x.RecentKifuInput
	}
	return nil
}

func (x *Input) GetPostKifuInput() *PostKifuInput {
	if x, ok := x.GetSelect().(*Input_PostKifuInput); ok {
		return x.PostKifuInput
	}
	return nil
}

func (x *Input) GetDeleteKifuInput() *DeleteKifuInput {
	if x, ok := x.GetSelect().(*Input_DeleteKifuInput); ok {
		return x.DeleteKifuInput
	}
	return nil
}

func (x *Input) GetGetKifuInput() *GetKifuInput {
	if x, ok := x.GetSelect().(*Input_GetKifuInput); ok {
		return x.GetKifuInput
	}
	return nil
}

func (x *Input) GetGetSamePositionsInput() *GetSamePositionsInput {
	if x, ok := x.GetSelect().(*Input_GetSamePositionsInput); ok {
		return x.GetSamePositionsInput
	}
	return nil
}

type isInput_Select interface {
	isInput_Select()
}

type Input_RecentKifuInput struct {
	RecentKifuInput *RecentKifuInput `protobuf:"bytes,1,opt,name=recent_kifu_input,json=recentKifuInput,proto3,oneof"`
}

type Input_PostKifuInput struct {
	PostKifuInput *PostKifuInput `protobuf:"bytes,2,opt,name=post_kifu_input,json=postKifuInput,proto3,oneof"`
}

type Input_DeleteKifuInput struct {
	DeleteKifuInput *DeleteKifuInput `protobuf:"bytes,3,opt,name=delete_kifu_input,json=deleteKifuInput,proto3,oneof"`
}

type Input_GetKifuInput struct {
	GetKifuInput *GetKifuInput `protobuf:"bytes,4,opt,name=get_kifu_input,json=getKifuInput,proto3,oneof"`
}

type Input_GetSamePositionsInput struct {
	GetSamePositionsInput *GetSamePositionsInput `protobuf:"bytes,5,opt,name=get_same_positions_input,json=getSamePositionsInput,proto3,oneof"`
}

func (*Input_RecentKifuInput) isInput_Select() {}

func (*Input_PostKifuInput) isInput_Select() {}

func (*Input_DeleteKifuInput) isInput_Select() {}

func (*Input_GetKifuInput) isInput_Select() {}

func (*Input_GetSamePositionsInput) isInput_Select() {}

type Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Select:
	//	*Output_RecentKifuOutput
	//	*Output_PostKifuOutput
	//	*Output_DeleteKifuOutput
	//	*Output_GetKifuOutput
	//	*Output_GetSamePositionsOutput
	Select isOutput_Select `protobuf_oneof:"select"`
}

func (x *Output) Reset() {
	*x = Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{15}
}

func (m *Output) GetSelect() isOutput_Select {
	if m != nil {
		return m.Select
	}
	return nil
}

func (x *Output) GetRecentKifuOutput() *RecentKifuOutput {
	if x, ok := x.GetSelect().(*Output_RecentKifuOutput); ok {
		return x.RecentKifuOutput
	}
	return nil
}

func (x *Output) GetPostKifuOutput() *PostKifuOutput {
	if x, ok := x.GetSelect().(*Output_PostKifuOutput); ok {
		return x.PostKifuOutput
	}
	return nil
}

func (x *Output) GetDeleteKifuOutput() *DeleteKifuOutput {
	if x, ok := x.GetSelect().(*Output_DeleteKifuOutput); ok {
		return x.DeleteKifuOutput
	}
	return nil
}

func (x *Output) GetGetKifuOutput() *GetKifuOutput {
	if x, ok := x.GetSelect().(*Output_GetKifuOutput); ok {
		return x.GetKifuOutput
	}
	return nil
}

func (x *Output) GetGetSamePositionsOutput() *GetSamePositionsOutput {
	if x, ok := x.GetSelect().(*Output_GetSamePositionsOutput); ok {
		return x.GetSamePositionsOutput
	}
	return nil
}

type isOutput_Select interface {
	isOutput_Select()
}

type Output_RecentKifuOutput struct {
	RecentKifuOutput *RecentKifuOutput `protobuf:"bytes,1,opt,name=recent_kifu_output,json=recentKifuOutput,proto3,oneof"`
}

type Output_PostKifuOutput struct {
	PostKifuOutput *PostKifuOutput `protobuf:"bytes,2,opt,name=post_kifu_output,json=postKifuOutput,proto3,oneof"`
}

type Output_DeleteKifuOutput struct {
	DeleteKifuOutput *DeleteKifuOutput `protobuf:"bytes,3,opt,name=delete_kifu_output,json=deleteKifuOutput,proto3,oneof"`
}

type Output_GetKifuOutput struct {
	GetKifuOutput *GetKifuOutput `protobuf:"bytes,4,opt,name=get_kifu_output,json=getKifuOutput,proto3,oneof"`
}

type Output_GetSamePositionsOutput struct {
	GetSamePositionsOutput *GetSamePositionsOutput `protobuf:"bytes,5,opt,name=get_same_positions_output,json=getSamePositionsOutput,proto3,oneof"`
}

func (*Output_RecentKifuOutput) isOutput_Select() {}

func (*Output_PostKifuOutput) isOutput_Select() {}

func (*Output_DeleteKifuOutput) isOutput_Select() {}

func (*Output_GetKifuOutput) isOutput_Select() {}

func (*Output_GetSamePositionsOutput) isOutput_Select() {}

type GetKifuOutput_Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Note string `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *GetKifuOutput_Player) Reset() {
	*x = GetKifuOutput_Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKifuOutput_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKifuOutput_Player) ProtoMessage() {}

func (x *GetKifuOutput_Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKifuOutput_Player.ProtoReflect.Descriptor instead.
func (*GetKifuOutput_Player) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetKifuOutput_Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetKifuOutput_Player) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type GetKifuOutput_Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq            int32             `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Position       string            `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Src            *Pos              `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty"`
	Dst            *Pos              `protobuf:"bytes,4,opt,name=dst,proto3" json:"dst,omitempty"`
	Piece          Piece_Id          `protobuf:"varint,5,opt,name=piece,proto3,enum=lambdakifu.Piece_Id" json:"piece,omitempty"`
	FinishedStatus FinishedStatus_Id `protobuf:"varint,6,opt,name=finished_status,json=finishedStatus,proto3,enum=lambdakifu.FinishedStatus_Id" json:"finished_status,omitempty"`
	Promoted       bool              `protobuf:"varint,7,opt,name=promoted,proto3" json:"promoted,omitempty"`
	Captured       Piece_Id          `protobuf:"varint,8,opt,name=captured,proto3,enum=lambdakifu.Piece_Id" json:"captured,omitempty"`
	TimestampSec   int32             `protobuf:"varint,9,opt,name=timestamp_sec,json=timestampSec,proto3" json:"timestamp_sec,omitempty"`
	ThinkingSec    int32             `protobuf:"varint,10,opt,name=thinking_sec,json=thinkingSec,proto3" json:"thinking_sec,omitempty"`
	Notes          []string          `protobuf:"bytes,11,rep,name=notes,proto3" json:"notes,omitempty"`
}

func (x *GetKifuOutput_Step) Reset() {
	*x = GetKifuOutput_Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKifuOutput_Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKifuOutput_Step) ProtoMessage() {}

func (x *GetKifuOutput_Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKifuOutput_Step.ProtoReflect.Descriptor instead.
func (*GetKifuOutput_Step) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{5, 1}
}

func (x *GetKifuOutput_Step) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetKifuOutput_Step) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *GetKifuOutput_Step) GetSrc() *Pos {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *GetKifuOutput_Step) GetDst() *Pos {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *GetKifuOutput_Step) GetPiece() Piece_Id {
	if x != nil {
		return x.Piece
	}
	return Piece_NULL
}

func (x *GetKifuOutput_Step) GetFinishedStatus() FinishedStatus_Id {
	if x != nil {
		return x.FinishedStatus
	}
	return FinishedStatus_NOT_FINISHED
}

func (x *GetKifuOutput_Step) GetPromoted() bool {
	if x != nil {
		return x.Promoted
	}
	return false
}

func (x *GetKifuOutput_Step) GetCaptured() Piece_Id {
	if x != nil {
		return x.Captured
	}
	return Piece_NULL
}

func (x *GetKifuOutput_Step) GetTimestampSec() int32 {
	if x != nil {
		return x.TimestampSec
	}
	return 0
}

func (x *GetKifuOutput_Step) GetThinkingSec() int32 {
	if x != nil {
		return x.ThinkingSec
	}
	return 0
}

func (x *GetKifuOutput_Step) GetNotes() []string {
	if x != nil {
		return x.Notes
	}
	return nil
}

type RecentKifuOutput_Kifu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KifuId        string   `protobuf:"bytes,2,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	StartTs       int64    `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Handicap      string   `protobuf:"bytes,4,opt,name=handicap,proto3" json:"handicap,omitempty"`
	GameName      string   `protobuf:"bytes,5,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	FirstPlayers  []string `protobuf:"bytes,6,rep,name=first_players,json=firstPlayers,proto3" json:"first_players,omitempty"`
	SecondPlayers []string `protobuf:"bytes,7,rep,name=second_players,json=secondPlayers,proto3" json:"second_players,omitempty"`
	Note          string   `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *RecentKifuOutput_Kifu) Reset() {
	*x = RecentKifuOutput_Kifu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecentKifuOutput_Kifu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentKifuOutput_Kifu) ProtoMessage() {}

func (x *RecentKifuOutput_Kifu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentKifuOutput_Kifu.ProtoReflect.Descriptor instead.
func (*RecentKifuOutput_Kifu) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{7, 0}
}

func (x *RecentKifuOutput_Kifu) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecentKifuOutput_Kifu) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

func (x *RecentKifuOutput_Kifu) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *RecentKifuOutput_Kifu) GetHandicap() string {
	if x != nil {
		return x.Handicap
	}
	return ""
}

func (x *RecentKifuOutput_Kifu) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *RecentKifuOutput_Kifu) GetFirstPlayers() []string {
	if x != nil {
		return x.FirstPlayers
	}
	return nil
}

func (x *RecentKifuOutput_Kifu) GetSecondPlayers() []string {
	if x != nil {
		return x.SecondPlayers
	}
	return nil
}

func (x *RecentKifuOutput_Kifu) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type GetSamePositionsOutput_Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq            int32             `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Src            *Pos              `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst            *Pos              `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Piece          Piece_Id          `protobuf:"varint,4,opt,name=piece,proto3,enum=lambdakifu.Piece_Id" json:"piece,omitempty"`
	Promoted       bool              `protobuf:"varint,5,opt,name=promoted,proto3" json:"promoted,omitempty"`
	FinishedStatus FinishedStatus_Id `protobuf:"varint,6,opt,name=finished_status,json=finishedStatus,proto3,enum=lambdakifu.FinishedStatus_Id" json:"finished_status,omitempty"`
}

func (x *GetSamePositionsOutput_Step) Reset() {
	*x = GetSamePositionsOutput_Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSamePositionsOutput_Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSamePositionsOutput_Step) ProtoMessage() {}

func (x *GetSamePositionsOutput_Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSamePositionsOutput_Step.ProtoReflect.Descriptor instead.
func (*GetSamePositionsOutput_Step) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{13, 0}
}

func (x *GetSamePositionsOutput_Step) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetSamePositionsOutput_Step) GetSrc() *Pos {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *GetSamePositionsOutput_Step) GetDst() *Pos {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *GetSamePositionsOutput_Step) GetPiece() Piece_Id {
	if x != nil {
		return x.Piece
	}
	return Piece_NULL
}

func (x *GetSamePositionsOutput_Step) GetPromoted() bool {
	if x != nil {
		return x.Promoted
	}
	return false
}

func (x *GetSamePositionsOutput_Step) GetFinishedStatus() FinishedStatus_Id {
	if x != nil {
		return x.FinishedStatus
	}
	return FinishedStatus_NOT_FINISHED
}

type GetSamePositionsOutput_Phase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string                         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KifuId string                         `protobuf:"bytes,2,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	Seq    int32                          `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Steps  []*GetSamePositionsOutput_Step `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
}

func (x *GetSamePositionsOutput_Phase) Reset() {
	*x = GetSamePositionsOutput_Phase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lambdakifu_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSamePositionsOutput_Phase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSamePositionsOutput_Phase) ProtoMessage() {}

func (x *GetSamePositionsOutput_Phase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lambdakifu_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSamePositionsOutput_Phase.ProtoReflect.Descriptor instead.
func (*GetSamePositionsOutput_Phase) Descriptor() ([]byte, []int) {
	return file_proto_lambdakifu_proto_rawDescGZIP(), []int{13, 1}
}

func (x *GetSamePositionsOutput_Phase) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSamePositionsOutput_Phase) GetKifuId() string {
	if x != nil {
		return x.KifuId
	}
	return ""
}

func (x *GetSamePositionsOutput_Phase) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetSamePositionsOutput_Phase) GetSteps() []*GetSamePositionsOutput_Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

var File_proto_lambdakifu_proto protoreflect.FileDescriptor

var file_proto_lambdakifu_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69,
	0x66, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61,
	0x6b, 0x69, 0x66, 0x75, 0x22, 0x40, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6b, 0x69, 0x66, 0x75, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0xaa, 0x01, 0x0a, 0x05, 0x50, 0x69,
	0x65, 0x63, 0x65, 0x22, 0xa0, 0x01, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55,
	0x4c, 0x4c, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x59, 0x4f, 0x4b, 0x55, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x48, 0x49, 0x53, 0x48, 0x41, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x59,
	0x55, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x41, 0x4b, 0x55, 0x10, 0x04, 0x12, 0x07, 0x0a,
	0x03, 0x55, 0x4d, 0x41, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x4b, 0x49, 0x4e, 0x10, 0x06, 0x12,
	0x07, 0x0a, 0x03, 0x47, 0x49, 0x4e, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x41, 0x52, 0x49,
	0x5f, 0x47, 0x49, 0x4e, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x4b, 0x45, 0x49, 0x10, 0x09, 0x12,
	0x0c, 0x0a, 0x08, 0x4e, 0x41, 0x52, 0x49, 0x5f, 0x4b, 0x45, 0x49, 0x10, 0x0a, 0x12, 0x08, 0x0a,
	0x04, 0x4b, 0x59, 0x4f, 0x55, 0x10, 0x0b, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x41, 0x52, 0x49, 0x5f,
	0x4b, 0x59, 0x4f, 0x55, 0x10, 0x0c, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x55, 0x10, 0x0d, 0x12, 0x06,
	0x0a, 0x02, 0x54, 0x4f, 0x10, 0x0e, 0x22, 0xb7, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x02, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x53, 0x50, 0x45, 0x4e, 0x44, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x53, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x44, 0x52, 0x41, 0x57, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x50, 0x45,
	0x54, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x52, 0x41, 0x57, 0x10, 0x04, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x4d, 0x41, 0x54, 0x45, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f,
	0x4f, 0x56, 0x45, 0x52, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10,
	0x06, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x4f, 0x55, 0x4c, 0x5f, 0x4c, 0x4f, 0x53, 0x53, 0x10, 0x07,
	0x12, 0x0c, 0x0a, 0x08, 0x46, 0x4f, 0x55, 0x4c, 0x5f, 0x57, 0x49, 0x4e, 0x10, 0x08, 0x12, 0x10,
	0x0a, 0x0c, 0x4e, 0x59, 0x55, 0x47, 0x59, 0x4f, 0x4b, 0x55, 0x5f, 0x57, 0x49, 0x4e, 0x10, 0x09,
	0x22, 0x31, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0xbe, 0x07, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6b, 0x69, 0x66, 0x75, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x54, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61, 0x6e,
	0x64, 0x69, 0x63, 0x61, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x61, 0x6e,
	0x64, 0x69, 0x63, 0x61, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x45, 0x0a, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x61, 0x6d, 0x62,
	0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0c, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x47, 0x0a, 0x0e, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47,
	0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x0d, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x12, 0x34, 0x0a, 0x0c, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64,
	0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0b, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x66, 0x65, 0x6e,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x66, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x73, 0x12, 0x34, 0x0a, 0x05, 0x73,
	0x74, 0x65, 0x70, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6c, 0x61, 0x6d,
	0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x1a, 0x30, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x1a, 0x9a, 0x03, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21,
	0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x61,
	0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x03, 0x73, 0x72,
	0x63, 0x12, 0x21, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50, 0x6f, 0x73, 0x52,
	0x03, 0x64, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75,
	0x2e, 0x50, 0x69, 0x65, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x52, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65,
	0x12, 0x46, 0x0a, 0x0f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6c, 0x61, 0x6d, 0x62,
	0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x49, 0x64, 0x52, 0x0e, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6d,
	0x6f, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x6d,
	0x6f, 0x74, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b,
	0x69, 0x66, 0x75, 0x2e, 0x50, 0x69, 0x65, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x52, 0x08, 0x63, 0x61,
	0x70, 0x74, 0x75, 0x72, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x53, 0x65, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x74,
	0x68, 0x69, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x74, 0x68, 0x69, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x63, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x6f, 0x74, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4b, 0x69,
	0x66, 0x75, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xba, 0x02, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x65, 0x6e,
	0x74, 0x4b, 0x69, 0x66, 0x75, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x37, 0x0a, 0x05, 0x6b,
	0x69, 0x66, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x61, 0x6d,
	0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4b, 0x69,
	0x66, 0x75, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x4b, 0x69, 0x66, 0x75, 0x52, 0x05, 0x6b,
	0x69, 0x66, 0x75, 0x73, 0x1a, 0xec, 0x01, 0x0a, 0x04, 0x4b, 0x69, 0x66, 0x75, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x66, 0x75, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x61,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0d, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x6f, 0x74, 0x65, 0x22, 0xf4, 0x01, 0x0a, 0x0d, 0x50, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x38, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64,
	0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x12, 0x3e, 0x0a, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66,
	0x75, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x2e,
	0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69,
	0x6e, 0x67, 0x22, 0x11, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x07, 0x0a, 0x03,
	0x4b, 0x49, 0x46, 0x10, 0x00, 0x22, 0x23, 0x0a, 0x08, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x54, 0x46, 0x38, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53,
	0x48, 0x49, 0x46, 0x54, 0x5f, 0x4a, 0x49, 0x53, 0x10, 0x01, 0x22, 0x29, 0x0a, 0x0e, 0x50, 0x6f,
	0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b,
	0x69, 0x66, 0x75, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x69, 0x66, 0x75, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x66, 0x75, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x66, 0x75, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x8c,
	0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74,
	0x65, 0x70, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x6b,
	0x69, 0x66, 0x75, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x65,
	0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x4b, 0x69, 0x66, 0x75, 0x49, 0x64, 0x73, 0x22, 0xf4, 0x03,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x06, 0x70, 0x68, 0x61, 0x73, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66,
	0x75, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x06,
	0x70, 0x68, 0x61, 0x73, 0x65, 0x73, 0x1a, 0xee, 0x01, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65,
	0x71, 0x12, 0x21, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50, 0x6f, 0x73, 0x52,
	0x03, 0x73, 0x72, 0x63, 0x12, 0x21, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x50,
	0x6f, 0x73, 0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x69, 0x65, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b,
	0x69, 0x66, 0x75, 0x2e, 0x50, 0x69, 0x65, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x52, 0x05, 0x70, 0x69,
	0x65, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x64, 0x12,
	0x46, 0x0a, 0x0f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64,
	0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x49, 0x64, 0x52, 0x0e, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x8a, 0x01, 0x0a, 0x05, 0x50, 0x68, 0x61, 0x73,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x69,
	0x66, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x66,
	0x75, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x3d, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66,
	0x75, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x05, 0x73,
	0x74, 0x65, 0x70, 0x73, 0x22, 0x8c, 0x03, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x49,
	0x0a, 0x11, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x61, 0x6d, 0x62,
	0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x66,
	0x75, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74,
	0x4b, 0x69, 0x66, 0x75, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x43, 0x0a, 0x0f, 0x70, 0x6f, 0x73,
	0x74, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52,
	0x0d, 0x70, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x49,
	0x0a, 0x11, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x61, 0x6d, 0x62,
	0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x66,
	0x75, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4b, 0x69, 0x66, 0x75, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x40, 0x0a, 0x0e, 0x67, 0x65, 0x74,
	0x5f, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47,
	0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x67,
	0x65, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x5c, 0x0a, 0x18, 0x67,
	0x65, 0x74, 0x5f, 0x73, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61,
	0x6d, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x48, 0x00, 0x52, 0x15, 0x67, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x22, 0x9c, 0x03, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x4c,
	0x0a, 0x12, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6c, 0x61, 0x6d,
	0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4b, 0x69,
	0x66, 0x75, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x10, 0x72, 0x65, 0x63, 0x65,
	0x6e, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x46, 0x0a, 0x10,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b,
	0x69, 0x66, 0x75, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x70, 0x6f, 0x73, 0x74, 0x4b, 0x69, 0x66, 0x75, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x4c, 0x0a, 0x12, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6b,
	0x69, 0x66, 0x75, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x66, 0x75, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00,
	0x52, 0x10, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x69, 0x66, 0x75, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x43, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x5f, 0x6b, 0x69, 0x66, 0x75, 0x5f, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x61,
	0x6d, 0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x66, 0x75,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x67, 0x65, 0x74, 0x4b, 0x69, 0x66,
	0x75, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x5f, 0x0a, 0x19, 0x67, 0x65, 0x74, 0x5f, 0x73,
	0x61, 0x6d, 0x65, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6c, 0x61, 0x6d,
	0x62, 0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00,
	0x52, 0x16, 0x67, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61, 0x6d, 0x62,
	0x64, 0x61, 0x6b, 0x69, 0x66, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lambdakifu_proto_rawDescOnce sync.Once
	file_proto_lambdakifu_proto_rawDescData = file_proto_lambdakifu_proto_rawDesc
)

func file_proto_lambdakifu_proto_rawDescGZIP() []byte {
	file_proto_lambdakifu_proto_rawDescOnce.Do(func() {
		file_proto_lambdakifu_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lambdakifu_proto_rawDescData)
	})
	return file_proto_lambdakifu_proto_rawDescData
}

var file_proto_lambdakifu_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_lambdakifu_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_lambdakifu_proto_goTypes = []interface{}{
	(Piece_Id)(0),                        // 0: lambdakifu.Piece.Id
	(FinishedStatus_Id)(0),               // 1: lambdakifu.FinishedStatus.Id
	(PostKifuInput_Format)(0),            // 2: lambdakifu.PostKifuInput.Format
	(PostKifuInput_Encoding)(0),          // 3: lambdakifu.PostKifuInput.Encoding
	(*GetKifuInput)(nil),                 // 4: lambdakifu.GetKifuInput
	(*Pos)(nil),                          // 5: lambdakifu.Pos
	(*Piece)(nil),                        // 6: lambdakifu.Piece
	(*FinishedStatus)(nil),               // 7: lambdakifu.FinishedStatus
	(*Value)(nil),                        // 8: lambdakifu.Value
	(*GetKifuOutput)(nil),                // 9: lambdakifu.GetKifuOutput
	(*RecentKifuInput)(nil),              // 10: lambdakifu.RecentKifuInput
	(*RecentKifuOutput)(nil),             // 11: lambdakifu.RecentKifuOutput
	(*PostKifuInput)(nil),                // 12: lambdakifu.PostKifuInput
	(*PostKifuOutput)(nil),               // 13: lambdakifu.PostKifuOutput
	(*DeleteKifuInput)(nil),              // 14: lambdakifu.DeleteKifuInput
	(*DeleteKifuOutput)(nil),             // 15: lambdakifu.DeleteKifuOutput
	(*GetSamePositionsInput)(nil),        // 16: lambdakifu.GetSamePositionsInput
	(*GetSamePositionsOutput)(nil),       // 17: lambdakifu.GetSamePositionsOutput
	(*Input)(nil),                        // 18: lambdakifu.Input
	(*Output)(nil),                       // 19: lambdakifu.Output
	(*GetKifuOutput_Player)(nil),         // 20: lambdakifu.GetKifuOutput.Player
	(*GetKifuOutput_Step)(nil),           // 21: lambdakifu.GetKifuOutput.Step
	(*RecentKifuOutput_Kifu)(nil),        // 22: lambdakifu.RecentKifuOutput.Kifu
	(*GetSamePositionsOutput_Step)(nil),  // 23: lambdakifu.GetSamePositionsOutput.Step
	(*GetSamePositionsOutput_Phase)(nil), // 24: lambdakifu.GetSamePositionsOutput.Phase
}
var file_proto_lambdakifu_proto_depIdxs = []int32{
	20, // 0: lambdakifu.GetKifuOutput.first_players:type_name -> lambdakifu.GetKifuOutput.Player
	20, // 1: lambdakifu.GetKifuOutput.second_players:type_name -> lambdakifu.GetKifuOutput.Player
	8,  // 2: lambdakifu.GetKifuOutput.other_fields:type_name -> lambdakifu.Value
	21, // 3: lambdakifu.GetKifuOutput.steps:type_name -> lambdakifu.GetKifuOutput.Step
	22, // 4: lambdakifu.RecentKifuOutput.kifus:type_name -> lambdakifu.RecentKifuOutput.Kifu
	2,  // 5: lambdakifu.PostKifuInput.format:type_name -> lambdakifu.PostKifuInput.Format
	3,  // 6: lambdakifu.PostKifuInput.encoding:type_name -> lambdakifu.PostKifuInput.Encoding
	24, // 7: lambdakifu.GetSamePositionsOutput.phases:type_name -> lambdakifu.GetSamePositionsOutput.Phase
	10, // 8: lambdakifu.Input.recent_kifu_input:type_name -> lambdakifu.RecentKifuInput
	12, // 9: lambdakifu.Input.post_kifu_input:type_name -> lambdakifu.PostKifuInput
	14, // 10: lambdakifu.Input.delete_kifu_input:type_name -> lambdakifu.DeleteKifuInput
	4,  // 11: lambdakifu.Input.get_kifu_input:type_name -> lambdakifu.GetKifuInput
	16, // 12: lambdakifu.Input.get_same_positions_input:type_name -> lambdakifu.GetSamePositionsInput
	11, // 13: lambdakifu.Output.recent_kifu_output:type_name -> lambdakifu.RecentKifuOutput
	13, // 14: lambdakifu.Output.post_kifu_output:type_name -> lambdakifu.PostKifuOutput
	15, // 15: lambdakifu.Output.delete_kifu_output:type_name -> lambdakifu.DeleteKifuOutput
	9,  // 16: lambdakifu.Output.get_kifu_output:type_name -> lambdakifu.GetKifuOutput
	17, // 17: lambdakifu.Output.get_same_positions_output:type_name -> lambdakifu.GetSamePositionsOutput
	5,  // 18: lambdakifu.GetKifuOutput.Step.src:type_name -> lambdakifu.Pos
	5,  // 19: lambdakifu.GetKifuOutput.Step.dst:type_name -> lambdakifu.Pos
	0,  // 20: lambdakifu.GetKifuOutput.Step.piece:type_name -> lambdakifu.Piece.Id
	1,  // 21: lambdakifu.GetKifuOutput.Step.finished_status:type_name -> lambdakifu.FinishedStatus.Id
	0,  // 22: lambdakifu.GetKifuOutput.Step.captured:type_name -> lambdakifu.Piece.Id
	5,  // 23: lambdakifu.GetSamePositionsOutput.Step.src:type_name -> lambdakifu.Pos
	5,  // 24: lambdakifu.GetSamePositionsOutput.Step.dst:type_name -> lambdakifu.Pos
	0,  // 25: lambdakifu.GetSamePositionsOutput.Step.piece:type_name -> lambdakifu.Piece.Id
	1,  // 26: lambdakifu.GetSamePositionsOutput.Step.finished_status:type_name -> lambdakifu.FinishedStatus.Id
	23, // 27: lambdakifu.GetSamePositionsOutput.Phase.steps:type_name -> lambdakifu.GetSamePositionsOutput.Step
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_lambdakifu_proto_init() }
func file_proto_lambdakifu_proto_init() {
	if File_proto_lambdakifu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lambdakifu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKifuInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Piece); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishedStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKifuOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecentKifuInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecentKifuOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostKifuInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostKifuOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKifuInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKifuOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSamePositionsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSamePositionsOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKifuOutput_Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKifuOutput_Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecentKifuOutput_Kifu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSamePositionsOutput_Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lambdakifu_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSamePositionsOutput_Phase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_lambdakifu_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*Input_RecentKifuInput)(nil),
		(*Input_PostKifuInput)(nil),
		(*Input_DeleteKifuInput)(nil),
		(*Input_GetKifuInput)(nil),
		(*Input_GetSamePositionsInput)(nil),
	}
	file_proto_lambdakifu_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*Output_RecentKifuOutput)(nil),
		(*Output_PostKifuOutput)(nil),
		(*Output_DeleteKifuOutput)(nil),
		(*Output_GetKifuOutput)(nil),
		(*Output_GetSamePositionsOutput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lambdakifu_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_lambdakifu_proto_goTypes,
		DependencyIndexes: file_proto_lambdakifu_proto_depIdxs,
		EnumInfos:         file_proto_lambdakifu_proto_enumTypes,
		MessageInfos:      file_proto_lambdakifu_proto_msgTypes,
	}.Build()
	File_proto_lambdakifu_proto = out.File
	file_proto_lambdakifu_proto_rawDesc = nil
	file_proto_lambdakifu_proto_goTypes = nil
	file_proto_lambdakifu_proto_depIdxs = nil
}
